app/assets/stylesheets/application.css

My default background colour for textareas is inherited from my OS
colours, which is a dark grey. Thus setting a foreground colour
without setting a background colour makes it impossible for me to type
in textareas. This patch should fix that.

Give textareas a default background colour.

---

app/views/layouts/application.html.erb

Since it keeps getting [asked](https://lobste.rs/s/gve5zg/why_does_the_lobsters_l_icon_change_color).
Of course open to different wording.

Add explanation of traffic number in logo title

---

app/models/story.rb

When extracting story domain, keep the facing `www\d*` domain in cases
where it's the only non top level domain (e.g. www31337.tld).
That may seem like an odd case, but i've seen a story on the www10.org domain today and it had a broken domain and, consequently wrong search by domain link.

Keep the www\d* domain for some stories

---

app/views/stories/_listdetail.html.erb

To encourage folks to write story descriptions on links, let's mark stories with descriptions so that folks know to click through.
The pilcrow is a little visually heavy, but it seemed better than an arbitrary symbol.

Indicate if a story has a description

---

app/views/stories/_listdetail.html.erb

For stories with both text and a link that have no comments, the only way to view the text is to either log in (no account :( ) or view the page source and find the story ID. This commit fixes that by always showing the comments link.

Show comments link even if there are no comments

---

app/views/stories/_listdetail.html.erb

(I couldn't find any indication that this was previously discussed and didn't feel like the effort involved was too great to avoid working on it before discussion, so... here's a PR. Close at will)
I love the recent addition of the 'authored by' checkbox, but unfortunately, the distinction between 'authored by' and 'by' is too subtle to be picked up without careful attention (at least for me). I tend to see 'by' as implicitly including 'authored ', because I don't tend to read the whole byline, just the '... by &lt;username&gt;.' Naturally, this leads to confusion on my part.
This PR makes a subtle change to the byline of stories. Instead of attempting to classify the type of attribution with a modifier (e.g. 'authored', or potentially 'submitted'), it avoids the use of 'by' all together …

Update byline for non-authored submissions.

---

app/assets/stylesheets/application.css

I am not entirely sure about this... but it feels like the `background-color: white;` on `.legend` is not intentional?
It currently creates a subtle odd appearance on pages like `/settings` and `/filters` where the section headers pop out because the background color is different than the rest of the page.

Remove white background from .legend

---

app/views/messages/index.html.erb

This PR moves the message creation box up above the message history box, so you don't have to scroll so far in order to get to it. It probably really would prefer just to be a lightbox.
This PR also reverses the order of the messages displayed so that the most recent ones show up on top first--this could probably be done in the controller, but fastest thing was just to reverse it in the view.
Thoughts?

Prettier messaging

---

app/assets/javascripts/application.js.erb

The select2 code failed to run after previewing a story
submission. This fix creates a new method that can be called upon
completion of the previewStory load() call.

Fixes #272. Add runSelect2 method to call after previewStory.

---

app/controllers/users_controller.rb

MySQL used to implement booleans as int(1) and preserves that behavior for backwards compatability. Postgres doesn't, so I was throwing 500s.
I audited all the other booleans, didn't catch any other use of 1 and 0.

Clean up mysqlism (booleans are also usable as int(1))

---

app/controllers/home_controller.rb
config/routes.rb

This makes their behaviour consistent with /newest and /t/:tag
Use case: I'd like to be able to trigger IFTTT events when I post stuff to lobste.rs, and the RSS feed would allow me to do that. I don't actually need the .json feed but it seemed to make more sense to have it behave the same way as the other pages that expose RSS feeds.
I couldn't find any tests for the RSS and JSON functionality, so I haven't added any for this either. If I've missed something, please let me know and I'll add some. I have run all the existing tests and this doesn't break anything. I've also tested it manually to verify that the JSON and RSS feeds work as expected.
I did this as a PR rather than an issue because it took all of five minutes and it seemed likely to be lower effort to just submit it as one than …

Add RSS and JSON feeds for newest by user

---

app/views/tags/index.html.erb

When mod is calculated, if stories_count of a tag is zero, 0 is divided by 0, giving NaN and a error. 
If stories_count of a tag is 0, divide by 1 instead thus this error is fixed. 
This will have prolonged difference since oncea tag gets atleast one story our pre-defined 1 won't be used.

Fix error when a tag has no stories yet

---

app/views/email_reply/mention.text.erb

Noticed this in the email notification: "amontalenti has mention you in a comment" -> "amontalenti mentioned you in a comment"

Typo fix: "has mention" -> "mentioned"

---

app/assets/stylesheets/application.css
app/views/comments/_commentbox.html.erb

Prevent comment textarea from exceeding width of container

---

app/assets/stylesheets/application.css
app/views/login/twofa.html.erb
app/views/settings/twofa_verify.html.erb

This hides the arrow buttons that WebKit displays for number inputs for TOTP code inputs.
E.g.,

Hide number input spinner buttons for TOTP inputs

---

Gemfile
Gemfile.lock
app/models/user.rb
extras/markdowner.rb
spec/models/markdowner_spec.rb

Fixes #288. We add CommonMark compatibility, strikethrough, `@username` expansion (with a kinda awkward AST walk, but it's simple if verbose), and with any luck general malleability going forward.

Use CommonMarker

---

app/views/global/_markdownhelp.html.erb

Looks like #354 landed, via #288,  which allows this to come back now.

Bring back strike through help.

---

Gemfile
Gemfile.lock

Resolves the following security issues (surfaced by `bundle-audit`)
- https://github.com/mishoo/UglifyJS2/issues/751
- https://groups.google.com/forum/#!topic/ruby-security-ann/aSbgDiwb24s
- https://groups.google.com/forum/#!topic/ruby-security-ann/XIZPbobuwaY
We launched [Dependabot](https://dependabot.com) on Lobsters last week with a blog post about dependency security, so I figured this was the least I could do to say thanks! :)

Upgrade nokogiri, jquery-rails and uglifier to secure version

---

app/views/stories/_listdetail.html.erb

"new" is a reserved keyword not allowed to use for browsing context in HTML5 (as well as HTML4 and XHTML) as per § 6.1.5 in the HTML5 specification. Instead use "_blank" to ensure a new browsing context. The use of "new" cause HTML validation of the frontpage to fail currently.

Use _target instead of _new in href target

---

spec/helpers/application_helper_spec.rb
spec/models/comment_spec.rb
spec/models/email_parser_spec.rb
spec/models/markdowner_spec.rb
spec/models/message_spec.rb
spec/models/story_spec.rb
spec/models/user_spec.rb
spec/models/vote_spec.rb
spec/spec_helper.rb

the :should syntax is no longer supported. Now we use the modern :expect syntax
This removes the deprecation warnings in the tests.

update rspec syntax

---

app/views/invitations/index.html.erb

Commit b592aae9 allowed the _Delete_ option for non-moderators, but didn't add the `<th></th>` to extend the grey tableheader bar over the new option. This adds an empty `<th>` cell like the one over _Send Invitation_.

Add tableheader for invite deletion

---

Gemfile

I got the following error until I added "json" to the Gemfile, when trying to install lobsters
rake db:schema:load
rake aborted!
LoadError: cannot load such file -- json
/home/ec2-user/.gem/ruby/2.3/gems/activesupport-5.1.1/lib/active_support/core_ext/object/json.rb:2:in `require'

added "json" to Gemfile

---

README.md

I got this error, and found that Nodejs install was the workaround.
[ec2-user@www lobsters]$ rake db:schema:load --trace
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'uglifier'.
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
found this solution here: https://stackoverflow.com/questions/34420554/there-was-an-error-while-trying-to-load-the-gem-uglifier-bundlergemrequire
hope this helps

added step of installing Nodejs, so uglifier works

---

app/views/comments/_comment.html.erb

Currently the delete, reply, and edit links on comments are skipped over when
using the tab key to flip through the various links. Adding an href allows tab
to navigate to these links, and `javascript:void(0)` prevents the page from
scrolling when these links are clicked.
Thanks again for the awesome site! Glad to make any edits to this you deem necessary, just thought I'd submit a quick patch since I noticed this the other day when using the site without a mouse.

Update delete, reply, edit links to be tabable

---

app/assets/stylesheets/application.css
app/assets/stylesheets/mobile.css
app/views/comments/_comment.html.erb
app/views/stories/show.html.erb

ref #189 
Based on mockup https://i.imgur.com/677PsUV.png from #233 
Current result (tested on Firefox / Ubuntu desktop only):
**Updated with narrower indentation**
[Previous screenshot](https://user-images.githubusercontent.com/87961/30788320-38a662bc-a14f-11e7-9b79-ca3d7cf80448.png)

Comment tree lines

---

app/assets/stylesheets/application.css

Fixes #406 
Also fixes the broken vertical padding when you go to a permalink like https://lobste.rs/s/qrlpqa/git_git_git_git_git#c_bh3ck6

comments: allow overflow for downvote why dialog

---

app/assets/javascripts/application.js.erb
app/assets/stylesheets/application.css

Here's a screenshot of the broken downvote menu:
The reduced opacity from comments with the 'bad'-class affects the
stacking order of its child elements and breaks the downvote menu. This
is avoided by appending the downvote reason menu below the comment
instead of inside it.

Fix broken downvote menu on bad comments

---

README.md

Code blocks now display without leading tabs which make it much easier to copy paste the yaml config into a new file when starting out. Plus there is now some code highlighting on the ruby and yaml sections.
I followed the readme for the initial setup but copy pasting the config settings was harder than it should of been.

Readme: Formatted code blocks to remove leading tabs

---

app/views/stories/show.html.erb

since they make it easy to confuse siblings for replies
-----
Example **before:**
User `test2` is replying to the original submission, but the tree lines connecting the top-level comments make it look like a reply to the first comment instead, causing unnecessary confusion.
Example **after:**

comments: hide top-level sibling tree lines

---

app/views/stories/_form.html.erb
app/views/stories/_form_errors.html.erb

also now only requires hitting Submit a single time,
instead of twice, if you already see the AJAX warning
Fixes #440

submit: fix resubmitting old URLs

---

config/application.rb

Any ruby requires that occur in your application will leak with
Pathnames in the $LOAD_PATH in ruby 2.3/2.4.  Beyond that, it's faster
to use strings in the load path.  Please join this bug and add your
support for a fix:
https://bugs.ruby-lang.org/issues/14372

Avoid require memory leak with pathnames in load path

---

config/initializers/email.rb

The changes made here does not affect how the older SMTP settings were configured. I have kept the earlier values as default and code won't break even if none of the environment values is not set.
I am curious how main lobsters site is running in production. Does this file is manually overwritten during deployment?

Make SMTP settings configurable from the env

---

app/models/search.rb
spec/models/search_spec.rb

When searching for a story a user can include a single tag:<tag_name>
element which will limit the scope of the search to that tag name.
This works similarly to the domain:<domain_name> feature which
limits the scope of the search to stories from that domain.
Examples:
"tag:python django" as a search query will search for stories
tagged with the python tag which reference the word "django".
"tag:python" will return all of the stories tagged with python
in the search results - which is essentially the /t/python page
but you can now order by Newest or Points as well.
Technical details:
* Added query parsing at the beginning of the search
to set a tag_scope string.
* When a tag_scope is set the relation gets another where clause
for only the tags that match exactly that scope.
* Modified the …

search: add tag scoped search

---

app/controllers/home_controller.rb

On a fresh install, this is how it looks:
This PR fixes above issue.

Bugfix: render privacy page properly

---

app/controllers/signup_controller.rb
app/views/layouts/application.html.erb
app/views/login/index.html.erb
app/views/signup/index.html.erb
app/views/signup/invited.html.erb
config/application.rb

This PR lets you have complete open sign ups and is configurable with an env var. Set `OPEN_SIGNUPS=true`, any other string or absence of this env will be considered as false. So, existing Lobsters instance will run as expected. 
Changes:
1. If `OPEN_SIGNUPS` is not set or set to any value other than `true`, app works like earlier.
2. If `OPEN_SIGNUPS` is set to `true`, in the header there will be an item `Sign Up Now` and in footer `Join <site name>`, they both point to `/invitations/open`. 
3. I added a new CSS class `signup-text` which can be used to customize `Sign Up Now` text in header.

Feature: Configurable open signups

---

app/assets/stylesheets/mobile.css
app/views/replies/show.html.erb

Pages like [search](https://lobste.rs/search) don't pad certain parts of the page on mobile devices (at least my browser), as can be seen in the following page:
My patch just adds the same margin as `.box`'s receive on mobile devices, to instances of `.help`. This means that the desktop UI stays the same. The only thing I had to do, was to add the `.help` tag to `div`s outside of a `div.box`, so that they also get the necessary padding. This might slightly change the appearance of some boxes, if this is a problem, I can try and find another way to fix it.\
**Note:** I couldn't test this "properly" since I don't have all the rails stuff installed, and basically have no idea what is necessary _to be installed_. My suggestions are purely based on playing around with the inspection tools on …

Fixed padding issue for some dialogs on mobile devices

---

Gemfile
Gemfile.lock
config/initializers/senic.rb

[scenic-mysql](https://github.com/rennanoliveira/scenic-mysql) hasn't been updated in a while and is missing code [to remove the table name from the view in the schema dump](https://github.com/EmpaticoOrg/scenic-mysql_adapter/blob/master/lib/scenic/adapters/my_sql.rb#L86). This should resolve:
* The db/schema.rb churn for new contributes
* Issues with setting up a new database from the schema

Use `scenic-mysql_adapter` over `scenic-mysql`

---

config/initializers/new_framework_defaults_5_2.rb

https://github.com/lobsters/lobsters/issues/509
from http://guides.rubyonrails.org/configuring.html
> config.action_controller.default_protect_from_forgery determines
> whether forgery protection is added on ActionController:Base. This is
> false by default, but enabled when loading defaults for Rails 5.2.
rails pull request: https://github.com/rails/rails/issues/29193

enable default_protect_from_forgery and use_authenticated_message_encryption

---

config/initializers/new_framework_defaults_5_2.rb
spec/rails_helper.rb

Fixes all of the individual configuration settings on https://github.com/lobsters/lobsters/issues/509
The next step will be to enable 5.2 defaults and remove these initializer files.
from the comments:
```
Use AES-256-GCM authenticated encryption for encrypted cookies.
Also, embed cookie expiry in signed or encrypted cookies for increased security.
This option is not backwards compatible with earlier Rails versions.
It's best enabled when your entire app is migrated and stable on 5.2.
Existing cookies will be converted on read then written with the new scheme.
```

enable use_authenticated_cookie_encryption

---

Gemfile
Gemfile.lock
app/models/search.rb
spec/models/search_spec.rb

Fix to issue [#491 Comment search doesn't use tag/domain scope.](https://github.com/lobsters/lobsters/issues/491).

filter by tag and domain when searching for comments

---

app/assets/stylesheets/application.css

Fixes: https://lobste.rs/s/wiwt7a/can_we_get_italics_work_within_block
Just tested this in the Firefox inspector

Don't italizice em tags inside blockquotes

---

app/models/story.rb

https://github.com/lobsters/lobsters/issues/522
Accessing tags from a story involves a database query. For records that haven't been persisted yet, resorting to fetch tags from the instantiated taggings.

Fix story tags not being rendered in preview

---

app/assets/javascripts/application.js.erb

Bind click event to comments OL container instead of existing elements.
Otherwise when creating the new comment it won't have the event attached
to it.

Fix #571 handle new comment

---

spec/rails_helper.rb

Before this change, running `Tag.destroy_all` would fail due to existing
`Moderation` records with a foreign key on some of those tags with the
following message:
```
Mysql2::Error:
Cannot delete or update a parent row: a foreign key constraint fails
(`lobsters_test`.`moderations`, CONSTRAINT `moderations_tag_id_fk`
FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`))
```
Thus, one had to manually cleanup some test data before re-running the test suite.

Fix failing test data cleanup due to foreign key constraint

---

app/views/stories/_listdetail.html.erb

The author entity was specified as a u-url instead of a u-author.
See https://chat.indieweb.org/dev/2018-10-18#t1539875247122800

Fix story author microformat tag

---

app/models/story.rb

DEPRECATION WARNING: Delegating exists to arel is deprecated and will be
removed in Rails 6.0. (called from block in <class:Story> at
./lobsters/app/models/story.rb:75)

Fix deprecation warnings for upcoming Rails 6

---

public/422.html
public/500.html

The error message wording on the 500 page isn't suitable for a site with the traffic lobste.rs now receives.  This patch makes the wording more descriptive and idiomatic, as well as providing guidance for reporting server side errors.

operational wording of error messages on HTTP error pages.

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

While the previous approach of hand-rolling test data cleanup + setup works
it’s prone to become insufficient with regards to future test scenarios. Recent
commits 6a6da094 and later 4620a922 highlight the issue.
Using the database cleaner gem provides a cleaner (pun intended) approach to
setup a clean room environment before and after each specific test.
Annotating specs with with `:js` or `:truncate` will switch from a transaction
based cleanup strategy to a truncation based one to enable feature/request specs
for which a web server is spun up in separate process by RSpec, in other words
the process executing the spec is not the same as the process handling the
request so RSpec/DatabaseCleaner wouldn’t know when to rollback the transaction.
The overall downside of this approach might be …

Switch to database cleaner approach for cleaning up test data

---

script/send_new_webmentions

Fix #586.
I've managed to reproduce it on the console:
```
2.3.3 :027 > a
=> "https://www.redhat.com/en/about/press-releases/ibm-acquire-red-hat-completely-changing-cloud-landscape-and-becoming-world’s-1-hybrid-cloud-provider" 
2.3.3 :028 > Sponge.new.fetch(a)
URI::InvalidURIError: URI must be ascii only "https://www.redhat.com/en/about/press-releases/ibm-acquire-red-hat-completely-changing-cloud-landscape-and-becoming-world\u{2019}s-1-hybrid-cloud-provider"
from (irb):28
2.3.3 :029 > Sponge.new.fetch(WEBrick::HTTPUtils.escape(a))
=> #<Net::HTTPOK 200 OK readbody=true> 
```

Fix invalid URI on script/send_new_webmentions

---

app/views/stories/_listdetail.html.erb

This patch avoids a double-closing `a` element.
It patch aligns _listdetail.html.erb with _similar.html.erb, where the closing `a` element is in each if-branch. Compare with https://github.com/lobsters/lobsters/blob/3ed2b8e5af0ce3d7d13c0e88104cacc045f3ed10/app/views/stories/_similar.html.erb#L16,L18

Move closing `a` element

---

app/controllers/stories_controller.rb
spec/controllers/stories_controller_spec.rb

Replacement for https://github.com/lobsters/lobsters/pull/555
Adds JSON support to the `check_url_dupe` endpoint allowing searches for discussions about previously submitted URLs.

Add JSON MIME to StoriesController#check_url_dupe

---

test/placeholder_test.rb
test/test_as_spec.rb

fix #585 
make `rails test` run `rails spec` instead

make `rails test` run `rails spec` instead

---

app/controllers/stories_controller.rb

Follow-up to https://github.com/lobsters/lobsters/pull/594 where I missed the authentication prevents queries against this endpoint for non-authenticated users.

Allow check_url_dupe to be queried for non-logged-in-users

---

app/models/story.rb

encode fetched_content response body from `ASCII-8BIT` to `UTF-8`

fix #590: encode fetched content to utf8

---

README.md

There is apparently a bug in the `mysql_config` script included in `mysql-connector-c` that the mysql2 gem uses to build the native extensions. This theoretically would trip up anyone using macOS 10.12+ without having MySQL or MariaDB running locally.

Notes mysql2 gem installation workaround for macOS

---

app/views/comments/_commentbox.html.erb

This caused the content of `comment.comment` to go into a `body` HTML attribute instead of the body of the textarea. This restores the functionality prior to 089f3475.
Closes #624 #625

Fix commentbox text_area

---

spec/features/comment_spec.rb

When the comment spec is run, on of the tests asserts that the
comment's text is a certain string. However that string was not
matching some of the time and causing the test to fail.
The reason is the comment factory has a sequence included in it. It
makes each successive comment look like this:
* "comment text 1"
* "comment text 2"
* "comment text 3"
* etc.
The test file was checking for the string: "comment text 5". When the
whole test file is run in isolation the failing test created a comment
and happened to be the 5th comment created. This let the test pass.
However if the test was run in isolation it would fail (comment text 1)
or when the test suite was run as a whole it would also fail (comment
text 11).
Now, instead of relying on a sequence to set the comment text, I've set
the …

Fix comment spec's order dependence

---

.travis.yml

This PR is about trying to **make the build pass:**
Before this change: it says "the Gemfile.lock _demands_ Bundler 2+" and quits. Example: https://travis-ci.org/lobsters/lobsters/builds/505896930
After this change: builds green.

CI: Get Bundler 2 first

---

app/assets/stylesheets/application.css

https://github.com/lobsters/lobsters/issues/640
It was easy beacuse .thread wasn't present apart from in the stylesheets

remove .thread dead code

---

app/models/tag.rb
spec/models/tag_spec.rb

Turns out `#new_record?` is only `true` before the save, which is not true in an `after_save` callback. I also made the unit tests a bit more specific.
Resolves #650

Fixes moderation logs for newly created Tags [Resolves #650]

---

app/models/story.rb
spec/models/story_spec.rb

~~I found it moderately difficult to write a test case for this, since it seems like all the tests I wrote seemed to assume UTF-8 encoding and passed the \xe2\x80\x99 apostrophe through just fine.~~ Regression test added.
Manual testing confirms that it works for the URL in #648 (https://www.codewithjason.com/sometimes-better-tests-hit-real-api/)
I can't locate Abdullah Samman, the last person to touch this line in 0e198cb9bf39211c22e5293d846e3e6be348e4f1, on GitHub, or I'd tag them as a reviewer.
~~Set to draft PR awaiting feedback on testing! I could spend a bit longer working on getting a test case written or we could just merge it.~~

Forces encoding to utf-8 when fetching url titles [Resolves #648]

---

app/assets/stylesheets/application.css

As discussed in #640.
The `div#hat_holder` and `img#party_hat` rules are defined in the [`lobsters-ansible`](https://github.com/lobsters/lobsters-ansible/blob/master/roles/lobsters/files/app/assets/stylesheets/local/lobsters.css) repository. Would you like me to open a PR there as well?

remove unused CSS rules

---

script/mail_new_activity.rb
spec/scripts/mail_new_activity_spec.rb

Unless we parse the text and figure out where the glyph boundaries are, we might end up splitting a glyph between bytes. Considering that was the original complaint in #328, I'm not sure what to do. Granted, the failing case I'm working with - a _really_ long word with multibyte characters - is probably unlikely, but still technically a possibility.
There's a failing test: `it 'handles really long words'` that covers this.
~~Submitting to publish the research / work I've done so far, but not particularly happy with it.~~
Resolves #328

Q-encode characters as multiple encoded words

---

app/views/home/about.html.erb

Migrated the original styles from https://userstyles.org to https://openusercss.org
Background information:
- Stylish and userstyles.org switched ownership(https://www.ghacks.net/2016/10/09/stylish-and-userstyles-org-have-a-new-owner/)
- Stylish is known to have privacy issues (https://en.wikipedia.org/wiki/Stylish#Privacy_issues)
- To avoid Stylish installation recommendation by userstyles.org, I migrated the themes to https://openusercss.org
The themes contain references to the original author, URL and licensing. The [Dark Lobsters](https://openusercss.org/theme/5cc5aeb3ad27da0c0016cf3d) theme had to be modified, as it was not working (white body background).
This is related to pull request https://github.com/lobsters/lobsters/pull/666

switch dark mode themes to openusercss

---

app/assets/stylesheets/application.css

The boxes are hard to read due to the black text on dark red background
colour (contrast ratio: 4.04).
This replaces the background colour with a light red one (ratio: 14.97)
for better readability.
Alternatively, could also muck about with the text colour, but this
looked better IMHO and it was easier to get a good contract ratio
(changing the text to #fff is more readable, but contrast ratio is only
5.19).

Better colours for error boxes

---

app/controllers/home_controller.rb
app/models/story_repository.rb
app/models/tag.rb
app/views/home/about.html.erb
app/views/home/index.html.erb
app/views/tags/_multi_tag_tip.html.erb
app/views/tags/index.html.erb
spec/features/homepage_spec.rb
spec/models/tag_spec.rb

Closes #525 (multi-tag based feed issue)
Builds off of and closes #542 (@sohaibbhatti's PR)
Design decisions:
- Use commas `,` to separate tags in the route parameters
- Validate that tags cannot have commas in them
- Use @sohaibbhatti's active record code snippet *
- Use `&ndash; <%= tag.description %>` only if tag description present
\* Regarding @sohaibbhatti's ActiveRecord code snippet, I was concerned that it might not produce the same output, but I ran an `EXPLAIN` on the MySQL queries that each command output (using `#to_sql`) and it came up with identical plans, so I think it's a fairly safe drop in replacement (more details [here](https://gist.github.com/briankung/83e636096d507b470b1f4120a05847cd))
All in all, not too much to do thanks to @sohaibbhatti's handiwork, unfortunate I …

#525 multi tag feed

---

.gitignore
Gemfile
Gemfile.lock

This is a follow-up on the collaboration between Lobsters and Scout + Nate Berkopec. 
Lobste.rs discussion thread here:
https://lobste.rs/s/5hshvd/proposal_lobste_rs_performance_analysis
In this PR, we've added Scout to the gemfile (referenced by git hash) and config/scout_apm.yml to .gitignore. 
The config file includes the organization's Scout key, so is not included here (e-mailing directly to @pushcx). It also includes the privacy features we've enabled as discussed in the Lobste.rs thread linked above, specifically the disabling of IP collection and query parameters.

Lobsters + Scout & Nate Berkopec Performance Collab

---

app/assets/javascripts/application.js.erb

comment_deletor/comment_undeletor: add missing event parameter to callback
This appears to be a C&P error introduced in
003d47ce221a4bc988b122804a8b7888e007c5f3 due to copying similar code
around here and forgetting to also modify the function parameters:
https://github.com/lobsters/lobsters/blob/003d47ce221a4bc988b122804a8b7888e007c5f3/app/assets/javascripts/application.js.erb#L545

comment_deletor/comment_undeletor: add missing event parameter to callback

---

Gemfile
Gemfile.lock

when running bundle I kept getting the following error:
```
The git source `git://github.com/scoutapp/scout_apm_ruby.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
```

update scout apm gem source to https

---

app/models/story.rb
extras/sponge.rb
script/send_new_webmentions

The `Sponge` class used to skip SSL certificate verification entirely
for all HTTPS calls for all HTTPS calls, which makes Lobsters
vulnerable to some MITM attacks that are easily exploited on private or
corporate LANs. We still want to skip certificate verification when
there's no specific security risk, but we do want to validate
certificates when communicating with well-known APIs, such as
Archive.is, GitHub, Gravatar and PushHover. Note that some APIs are
accessed outside of Sponge, such as Twitter's one.
Turning this verification on will flat out break requests to those
websites in case their certificate expired or is incorrect. This may
trigger a 500 for the users of Lobsters, which is what we want. Note
that for Gravatar the 500 would be limited to avatar serving, and
wouldn't …

Turn SSL certificate verification on for critical services

---

app/controllers/stories_controller.rb
app/models/hidden_story.rb
app/models/read_ribbon.rb

This PR aims at fixing #675.
As said in the issue, ReadRibbon for a given story is marked as "is_following = false" when hiding the story, making replies not displayed in the "Replies" section. But when unhiding a story we don't mark it back as "is_following = true", hence the problem.
The PR also has 2 small refactor commits that are neutral from a behavior point of vue but make the code a bit more coherent.
HiddenStory and ReadRibbon related behaviors were not tested previously. We may want to add a test, it might be a bit tautological but let me know, I can give it a try.
Of course feel free to tell me what to improve in this proposal!

Fix replies missing after unhiding story

---

app/views/comments/_commentbox.html.erb
app/views/filters/index.html.erb
app/views/hats/build_request.html.erb
app/views/hats/requests_index.html.erb
app/views/invitations/build.html.erb
app/views/invitations/index.html.erb
app/views/keybase_proofs/new.html.erb
app/views/login/forgot_password.html.erb
app/views/login/index.html.erb
app/views/login/set_new_password.html.erb
app/views/login/twofa.html.erb
app/views/messages/_form.html.erb
app/views/messages/index.html.erb
app/views/messages/show.html.erb
app/views/mod_notes/index.html.erb
app/views/moderations/index.html.erb
app/views/search/index.html.erb
app/views/settings/index.html.erb
app/views/settings/twofa.html.erb
app/views/settings/twofa_verify.html.erb
app/views/signup/invited.html.erb
app/views/stories/_form_errors.html.erb
app/views/stories/edit.html.erb
app/views/stories/new.html.erb
app/views/stories/suggest.html.erb
app/views/tags/_form.html.erb
app/views/users/_invitationform.html.erb
app/views/users/show.html.erb
config/application.rb

Now that https://github.com/lobsters/lobsters/issues/527 has been closed, we can use the default value for `action_view.form_with_generates_remote_forms` which is true, and conforms to the defaults of rails. This should remove surprises for people browsing the code.
I also took the time to make the style more consistent.
This also opens up the opportunity for someone to experiment with turning 1 form into a remote form without having to convert them all.

set action_view.form_with_generates_remote_forms to default (true)

---

README.md

The external Docker project is still maintained,
but was moved into a github org.

Update docker link in README.md

---

app/controllers/stories_controller.rb
spec/controllers/stories_controller_spec.rb
spec/features/read_story_spec.rb

Attempt to fix #706.
Using the example from the bug report, a request to `https://lobste.rs/s/2ftw37.json` will now return a 302 to `https://lobste.rs/stories/sfo06b.json`

Properly redirect json requests for a merged story's show page

---

app/controllers/login_controller.rb
app/models/user.rb

Fix bug preventing the inactive-user user account from being created by *rake db:seed* as well as preventing the inactive-user user to reset their password.

Fix bug preventing the inactive-user user to reset their password

---

app/models/invitation.rb
app/models/invitation_request.rb

Creating codes for invitations and invitation requests should raise on
the 10th attempt.
The "too many hash collisions" exception is never raised because the 10th try never happens. Using the inclusive range operator, instead of the exclusive one, makes it work.
Aside: the code columns for these models are missing a unique index. Is it worth adding or are too few concurrent creates for invitations and invitation requests for that to matter?

bugfix: actually raise on too many code collisions

---

config/initializers/content_security_policy.rb
spec/requests/content_security_policy_spec.rb

Now that enough time has passed since https://github.com/lobsters/lobsters/pull/698 we should enable the enforcement of the content security policy.
I also added a requests (as discussed in https://github.com/lobsters/lobsters/issues/704) test for csp so that the headers get their own tests.

enforce content security policy

---

app/models/vote.rb

Add a new option "Unkind" when down-voting comments.
As brought up here: https://lobste.rs/s/xnjo8g/add_downvote_reason_unkind
As mentioned in https://lobste.rs/s/xnjo8g/add_downvote_reason_unkind#c_0lzrxb, this is maybe related to https://github.com/lobsters/lobsters/issues/376?
Does the phrasing need to be 100% figured out before any merging? The intent - which seems generally clear - seems important, and if it's being stored as a single character then we can easily adjust language as necessary later?
Note: I used "me-too" as a search term to see if there are any specific tests for this, and the me-too case didn't seem to have any. So, no tests here but happy to add some if people have ideas for what is testable here!
Also, I'm wondering if this requires consideration here? …

Add "Unkind" option

---

config/initializers/content_security_policy.rb
spec/requests/content_security_policy_spec.rb

Hopefully fixing the issues described at https://github.com/lobsters/lobsters/pull/737
Added `connect_src :self` to fix the commenting issues.
Also found an additional case that we have to handle when submitting stories.
Unfortunately it performs an eval when previewing a story submission, so we have to enable that as well.
Finally, I learned that we have a comment spec which should have caught the posting issue, but it succeeded so my guess is that capybara tests do not enforce content security policies during a test which is a bummer.

csp (attempt 2)

---

app/models/invitation.rb
app/models/invitation_request.rb
spec/factories/invitation.rb
spec/factories/invitation_request.rb
spec/models/invitation_request_spec.rb
spec/models/invitation_spec.rb

This adds validation and tests for the `Invitation` and `InvitationRequest` models to fix some parts of #745

Add validation for invitation and invitation request

---

Gemfile
Gemfile.lock

Update the Scout APM gem to the latest version so that the Timeline view can be utilised.
https://docs.scoutapm.com/?_ga=2.117993099.324453617.1571089242-2135995770.1562204706#updating-to-the-newest-version

Update Scout gem to the latest version

---

app/models/story.rb
spec/fixtures/story_pages/3.html
spec/fixtures/story_pages/4.html
spec/models/story_spec.rb

This addresses https://github.com/lobsters/lobsters/issues/368 
Do not use the rel=canonical attribute if it is
1) unparseable by URI
2) parseable but resolves to the domain root (eg "google.com/")
3) parseable, but returns a non-200 level response code when retrieved via GET
This PR adds 2 fixture files which are the same aside from their rel=canonical attribute; if confusing, it is trivial to use different source sites for 3.html and 4.html (or perhaps they can be stripped down to merely their canonical attributes).
(This page was chosen out of autocomplete laziness / clicking what at the moment was the top-leftmost thing on mcsweeneys)

do not use bad canonical links

---

app/assets/javascripts/application.js.erb

When visiting https://lobste.rs/stories/new there is a JS console error
```
TypeError: e.match(...) is null
```
this happens because it tries to match stories title even when the title is empty. This is a simple fix to not try to match against empty titles

fix: don't try to match empty title

---

db/migrate/20191029021735_fix_database_consistency_with_validators.rb
db/schema.rb

Issue #745 
Setting not NULL constraint for:
- Table 'hat_requests', columns 'hat', 'link', 'comment'
- Table 'invitation_requests', columns 'name', 'email'
Don't know why `collation: "utf8mb4_general_ci"` disappeared, should I add it by hand?
Also don't know why `replying_comments` changed, do you prefer that I remove that change from the commit or should I leave it?

Updating not null constraint on columns with presence validator

---

app/models/story.rb

The archive.is website is not accessible in Russia. Using archive.md is fine.
See https://blocklist.rkn.gov.ru/ (enter archive.is in URL field).
Have no idea why that happened though.

Use archive.md instead of archive.is

---

app/models/keystore.rb
app/models/message.rb
app/models/mod_note.rb
app/models/moderation.rb
db/migrate/20191008123620_add_foreign_key_for_messages_and_comments.rb
db/migrate/20191010172004_add_index_for_moderations_associated_model.rb
db/schema.rb
spec/models/keystore_spec.rb
spec/models/message_spec.rb
spec/models/mod_note_spec.rb
spec/models/moderation_spec.rb

===================================================
===================================================
Also can be marked as done, as i told [before](https://github.com/lobsters/lobsters/issues/745#issuecomment-539024662):

Add validations into models(#745)

---

app/views/stories/_listdetail.html.erb

We aleady add rel=nofollow to links in our comments. This
does the same thing for stories following the newest Google recomendations.
https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html

Mark story links as user generated content

---

extras/github.rb

https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/
Fixes #819

passing Github access token in header instead of query parameter

---

lib/tasks/fake_data.rake

fake_data failed to run with following errors:
```
$ rails fake_data
rails aborted!
ActiveRecord::RecordInvalid: Validation failed: Url is an unseen domain from a new user
/home/favadi/code/personal/lobsters/lib/tasks/fake_data.rake:30:in `block in generate'
/home/favadi/code/personal/lobsters/lib/tasks/fake_data.rake:25:in `times'
/home/favadi/code/personal/lobsters/lib/tasks/fake_data.rake:25:in `generate'
/home/favadi/code/personal/lobsters/lib/tasks/fake_data.rake:100:in `block in <top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => fake_data
(See full trace by running task with --trace)
```
Fixed by changing fake user created_at to NEW_USER_DAYS.days.ago.

fix fake_data failed at User.is_new? validator

---

public/500.html

In case of 500 errors it's very likely that the link to `/chat` would also lead to a 500 error. This PR changes the link directly to the IRC channel.

Replace link to IRC channel in 500 error message

---

app/views/home/chat.html.erb

freenode.net doesn't capitalize the name anywhere on the site.

/chat: freenode is not capitalized, despite being a proper name.

---

app/models/user.rb

Resolves https://github.com/lobsters/lobsters/issues/771
When a user is inactive, [`User#refresh_counst!`](https://github.com/lobsters/lobsters/blob/791b21f60a2e952cabe5187559c8fb7724b7b8aa/app/models/user.rb#L344) is called. This method updates `user:#{self.id}:stories_submitted` with the value from `self.stories.not_deleted.count`.
When a user deletes a story and then deactivates the account, the value for `user:#{self.id}:stories_submitted` will be the number of stories submitted minus the number of stories deleted.
When the info of the user is displayed, [`stories_displayed`](https://github.com/lobsters/lobsters/blob/master/app/helpers/users_helper.rb#L7) already takes into account the stories that have been deleted.
So if a user submits 1 story and then removes it, …

Fix error refreshing stories count

---

app/controllers/home_controller.rb
spec/controllers/home_controller_spec.rb

Lobste.rs has a [page of a user's upvoted stories](https://lobste.rs/upvoted/stories), which includes an RSS feed. Most of Lobste.rs' feeds can authenticate a user via a `?token=` URL parameter, so feed readers can retrieve them without needing a user's session cookie. This was missing for upvoted stories; requests for the RSS feed redirect to the Lobste.rs login page.
This PR fixes this bug, and includes a test case to demonstrate it works as expected.

Support token-based access for the RSS feed of upvoted stories

---

app/models/story.rb
spec/models/story_spec.rb

Continuing from discussion here: https://github.com/lobsters/lobsters/pull/880/
I am assuming front page is the literal list of articles on the home page.
Currently '/recent' filtering is just grabbing _low_ rated stories(?). 
https://github.com/lobsters/lobsters/blob/86fb86788e3afa4de4b8a10d25fd09785897b0dd/app/models/story.rb#L43
https://github.com/lobsters/lobsters/blob/86fb86788e3afa4de4b8a10d25fd09785897b0dd/app/models/story.rb#L50-L56
Not sure if this is intentional so I left it for now.
Front page articles are now properly filtered out with this PR.

Filter out front page posts from 'recent'

---

app/assets/javascripts/application.js.erb
app/views/stories/_form.html.erb

Use a `<details>` tag for the story guidelines on the story submission page, instead of an anchor tag with a click handler. This improves accessibility, and is related to #755.
Collapsed:
Expanded:
I wanted to contribute back to Lobsters (which has been an amazing community). This seemed like a straightforward change to make as my first one to this project.
https://github.com/lobsters/lobsters/issues/755#issuecomment-538805549 rightfully indicates an aversion to bike-shedding, and I think this is a clear accessibility win, because
- Assistive technology will indicate that there's more content, and whether it's expanded or collapsed.
- We avoid an anchor tag, which generally is expected to navigate to another url or another location on this page. That's not really what's happening here. …

Use a details tag for the story guidelines

---

app/controllers/comments_controller.rb
app/controllers/stories_controller.rb
config/routes.rb
spec/models/tag_spec.rb

The new reconciliation process between an object's Vote and its
memoized count requires that MariaDB can see the records in the Vote
table. Currently, we are seeing the vote be created, then the
memoization for new comments and stories to zero.
We now force this behavior to take place inside of a transaction.
This should keep the code working the way we expect.

Wrap Story and Comment creation inside of a transcation.

---

app/views/mod/_nav.html.erb

Rather than mod_flagged_path, call mod_flagged_stories_path or
mod_flagged_comments_path depending on context. This is part of
renaming comment downvotes to flags, just as we do stories.

/mod: use story/comment specific mod_flagged_path call.

---

app/controllers/comments_controller.rb
app/models/comment.rb
spec/features/comment_spec.rb
spec/models/comment_spec.rb

As quoted in #864, i change the `for_user`scope to `accessible_to_user` 
I also change the condition `user && user.is_moderator?` to ` user&.is_moderator?`

rename comment scope

---

app/models/user.rb

The code to compute a user's most common tags to display on their profile page doesn't take into account the state of the story, leading to users being able to have 0 stories, yet a most common tag for those 0 stories, as evidenced in Bug #893. This change edits `lobsters/app/models/user.rb` to have `most_common_story_tag` take into account the `is_expired` nature of the story and ensure the story is still visible. 
https://github.com/threeplanetssoftware/lobsters/blob/87dc77fe7ef3989045fd2fbea96c4a0e38aee052/app/models/user.rb#L494
This pull request should fix #893, unless it is intended behavior for expired posts to be included in these calculations. If that is the case this can be tossed out and the bug report closed as a feature.

Fixes bug #893 by not considering tags on expired stories.

---

app/models/hat.rb
app/views/hats/index.html.erb
spec/features/hatpage_spec.rb
spec/models/hat_spec.rb

This checks that a user is logged in before showing the hat's link on
the hat index page.  This change is needed because a malicious anonymous
user scraped the page and send a user spam based on the email found on
it.
Issue: #854

Updates hats index view

---

app/views/comments/_comment.html.erb

On /comments, when logged in as a moderator and when a comment has
received no upvotes or flags, a trailing pipe (|) appears in the
byline.
Once a comment is upvoted, the spurious pipe (|) disappears.
Do not display this character when the vote summary is the empty
string.

comments: remove dangling pipe (|) when vote_summary_for_user is empty.

---

config/initializers/production.rb.sample

StoryCacher was renamed to DiffBot but the sample configuration
was not brought up-to-date.

production.rb.sample: s/StoryCacher/DiffBot/

---

.rubocop.yml
app/controllers/application_controller.rb

Without these changes, rubocop prints out:
```
$ bundle exec rubocop
Inspecting 172 files
.app/controllers/application_controller.rb: Metrics/LineLength has the wrong namespace - should be Layout
app/controllers/application_controller.rb: Metrics/LineLength has the wrong namespace - should be Layout
...........................................................................................................................................................................
172 files inspected, no offenses detected
The command "bundle exec rubocop" exited with 0.
```

fix wrong namespace for LineLength

---

lib/tasks/fake_data.rake

This fixes #914 by creating test Categories during `rails fake_data` and pulling those randomly in to the creation of new Tags. 
**Note**: This does not use `find_and_create_by!` for Tags since that could attempt to create another tag with the same name if the random Category is different. Instead it checks for an existing tag (regardless of Category) and, if that is not found, then tries to create a new tag. 
This also updates `rails fake_data` to use the newer Faker::Lorem syntax, specifying the parameter name in .sentences() and .paragraphs(). This is a follow-on from the work in #881.

Update fake_data to create test Categories and pass those in to new Tags

---

app/models/comment.rb

A null score, present when there are no votes for a comment,
causes an ActiveRecord::NotNullViolation.

when there are no votes for a comment, score is 0 not NULL.

---

app/views/messages/_form.html.erb

Fixes #927 by only allowing wearable hats to populate the message reply form. Copied the syntax from the comment reply box to ensure consistency.

Update message reply form to only include wearable hats. 

---

app/views/comments/_comment.html.erb

The byline, where logged in users might variously have the option
to flag or unflag a comment, displays a spurious pipe (|) to readers
without the option to flag.
Remove that, retaining the stub span.

Remove double pipe (| |) in comment byline for those not logged in.

---

script/mail_new_activity.rb

Currently, there is no way to tell whether a story has been authored by a submitter or not from the e-mail that is received when one subscribes to the mailing list. This information can be useful for
1. Marking a story as authored by the submitter in things like mockturtle;
2. Filtering out authored articles at the user's preference.
The `X-Is-Author` header will be `true` when the submitter of the story checks the "Authored" box, and `false` otherwise.

Add X-Is-Author to mailing list headers

---

app/assets/javascripts/application.js.erb

1. Write your comment, post it.
2. Press F5
3. The reply field now contains your comment, since it was submitted and
hidden via JS, and Firefox will still re-populate it after reloading.
This only happens in Firefox; Chrome doesn't have this behaviour.

Clear reply textarea after posting

---

app/assets/stylesheets/application.css

Flash banners (of green success, red error, and blue notice types) have yellow default coloring that's always overridden, gradients we never see due to syntax errors, and some properties set twice in one class such that their first value is never used. This change reduces the bulk of that CSS while keeping appearance unchanged.
Before:
After:
…as captured by Safari Technology Preview web inspector.
This is a side issue discovered while working on #637.

Reduce unused CSS properties in flash banners

---

app/views/home/about.html.erb

This tag appears gray normally, but was yellow where specifically included in /about.

Use meta tag style on about page meta tag

---

app/assets/stylesheets/application.css
app/assets/stylesheets/mobile.css

Markup matching those selectors appears not to be emitted since downvote arrows were removed.
"voters" is this whole element:
"upvoter" is the up arrow. There was once a downvote arrow as well, named "downvoter". It was removed in 9535b05, but its CSS is still here. The term "downvote" appears to have been replaced with "flag" back in 20c1590, so the CSS more recently referred to a "flagger".
This is a side issue discovered while working on #637.

Remove CSS references to "flagger" within "voters"

---

app/assets/stylesheets/application.css
app/assets/stylesheets/local/lobsters.css
app/assets/stylesheets/mobile.css

In response to the [bikeshed thread](https://lobste.rs/s/eg1n75/dark_mode) following #1026, this revision:
- Brightens the dark mode background color just a little, and box/table/hat elements to match.
- Caps dark mode text contrast at 10:1. This is most noticeable on body text which previously was about 15:1.
- Otherwise maintains the same contrast in all of dark mode's uncolored text.
- Closes #1030.
- Darkens the visited link color in light mode to hit WCAG AA minimum 4.5:1 contrast.
- Darkens the unvisited link color in light mode to keep visited links feeling just as distinct.
I think the dark mode link and visited link colors could stand improvement, but wanted to deliver this before stepping away for a long weekend. I suggest merging this if there are no showstopping issues and …

Dark mode revision

---

app/controllers/replies_controller.rb
app/controllers/settings_controller.rb
app/views/layouts/application.html.erb

Other top nav links are highlighted when their pages are displayed. These two may have been overlooked.
Replies, before:
Replies, after:
Settings, after:

Highlight replies and user settings links in top nav

---

app/models/story.rb

Sourced from:
https://support.google.com/google-ads/answer/9744275?hl=en
https://support.google.com/optimize/answer/6361119?hl=en#zippy=%2Cexample-parameters-in-redirect-destination-dont-conflict

Add additional tracking query parameters 

---

app/models/user.rb
app/views/users/show.html.erb
spec/models/user_spec.rb

I thought it would be nice to allow Gemini spaces and Gopher holes in the homepage field.

Allow gemini and gopher homepage URLs

---

app/assets/javascripts/application.js.erb

Assume that it's HTTP if nothing was specified. Validation happens elsewhere already, so instead of duplicating that here, just add a scheme if it's missing.
Related to #944.

Add 'http://' to homepage only when it lacks a scheme

---

app/assets/stylesheets/application.css.erb

Closes #1062
I don't really know what I'm doing. I just switched the position options around in the affected CSS until it looked okay. I would like people to be able to flag my comments more effectively, though, so here's a fix 🎁

Fixes comment flag bug, closes #1062

---

.github/workflows/check.yml

This starts a Docker container running MariaDB instead of using the MySQL database that GitHub Actions comes with. This means we can configure which specific version of MariaDB to run.
I opted for MariaDB 10.5 as that was my best guess as to what version was running in the deployed setup, based on it being the version available for the "mariadb-server" package in Debian stable.
The Docker container is configured to create the "lobsters_dev" database automatically, so it shouldn't be necessary to run a command to explicitly create the database anymore.
Fixes #1050.

Use MariaDB instead of MySQL when running tests in GitHub Actions

---

app/models/message.rb
app/models/mod_note.rb
db/migrate/20220331165136_message_author_nullable.rb
db/schema.rb
spec/models/story_spec.rb

This also fixes a (unknown?) bug where users do not receive a message if a suggestion on one of their stories was auto-accepted due to quorum.
I implemented this in a kind of TDD style. As stated above, at the moment, users don't get sent any message if a suggestion was auto-accepted. This is because the created message has no author, which causes an error when the message is saved. So I created a test for that first, then made the `author` field nullable in messages.
**Summary of changes:**
- Add tests for auto-accepting suggestions on stories.
- Make author_user_id nullable in messages.
- Fix mod note creation in case message has no author.

Fix #1049 Can't delete system messages

---

app/models/comment.rb
app/models/story.rb

Intended for clients that don't need to (or can't) handle HTML, and can render (or simply display) the raw markdown themselves. Fixes #972

Plain text in comments and stories

---

lib/tasks/fake_data.rake

Generate unban reason for fake data. Was able to successfully run `rails fake_data` afterwards.

Fix #1087: Add unban reason to fake data

---

app/assets/javascripts/application.js.erb
app/assets/stylesheets/application.css.erb
app/views/global/_markdownhelp.html.erb

I am in the process of removing the jQuery as mentioned in #554. This will streamline the site and drop the large dependency when it is finished.
I have started with the functions in `$(document).ready()`.  Those functions aren't tied into the `Lobsters` class and are easy to isolate and replace individually. Later steps will replace the `Lobsters` class and require minor editing to the changes included in this pull request, but should have no effect on the functionality of the site.
These edits also create new functions in JavaScript that replace: `.ready()`, `.parent()`, `.replaceWith()`, & `.on()` jQuery functions.
This pull request also:
- fixes #1082 
- triggered the guideline instructions when you fetch a title before submitting a new story.
This is incomplete, but I wanted feedback …

Begin removing jQuery (#554)

---

app/assets/javascripts/application.js.erb

This is part two of removing jQuery as a part of #554. 
I added a new function `fetchWithCSRF` which is required for the CSRF token as plain JS requires a little more handling than jQuery to validate requests.
This pull request also adds a `removeExtraInput` function that fixes a bug, in which various calls to the backend result in an additional input being added to the site.  It hasn't been a problem as they are `display: none` so no one has noticed.  However, if you make changes in a particular order on a comment it can become hidden until you reload the page. 
I will post another update next week.

Continuing to remove the jQuery #554

---

app/assets/javascripts/application.js.erb

Part 3 in the removal of jQuery.
I created the new Lobster class to replace the Lobsters class and make the transition easier. I pre-generated the functions that I need to replace and made notes as to which functions rely on other functions.
I identified and labeled a bug in the `checkStoryDuplicate` function.  I won't fix it until I rewrite the function to remove the jQuery. 
Removed jQuery from:
- Posting comments
- Account page Homepage URL entry
- The call to `checkStoryTitle`
Noted problems with this pull request:
- I put a bug into the post comment function when you edit/update a comment.  I added another commit to fix that issue.

Continuing to remove the jQuery #554 part III

---

app/assets/javascripts/application.js.erb
app/assets/javascripts/autosize.js
app/assets/stylesheets/application.css.erb
app/views/stories/show.html.erb

This request includes:
Replacing the:
-  vote()
-  saveStory()
-  hideStory()
-  checkStoryTitle() - Partial replacement due to select2
-  bounceToLogin()
-  checkStoryDuplication()
-  previewComment()
It also:
-  Removes an embedded script tag that is no longer required.
-  Creates a slideDownJS() to replace jQuery slideDown()
-  Updates AutoSize()

Replacing 7 functions to further the removal of jQuery (#554)

---

app/assets/javascripts/application.js.erb
app/assets/stylesheets/application.css.erb
app/views/stories/new.html.erb

The vote function was used for both stories & comments to process both voting them up & flagging them.  This allowed for a lot of bugs and required onClick event functions to be created within the function, instead of as an onPageLoad event.
This pull request is step 1 of a 2 step process to split the voting into separate functions for stories or comments.  It will also reduce the chance of errors by reducing the number of params passed. Instead the functions will internally know if they are handling a story or comment, rather than searching the DOM to determine what type of element it is handling .
This will double some of the code but remove complexity and chance for errors. I can later reduce some of the duplication in the follow up pull request.
This pull request includes:
Functions …

Refactoring and removing jQuery from the vote function 

---

app/assets/javascripts/application.js.erb

This will fix a few bugs that fell into production during the migration away from jQuery.
- fetching the url title when it is blank
- putting a warning up for a duplicate url over 30 days old
- pressing the preview story button a second time

Fix js bugs in the story functions from removing the jQuery

---

app/views/tags/index.html.erb

This PR contains two minor HTML related fixes for the tag list (`/tags`).
* Fix unexpected nested `<ol>` elements for tag list.
* Use `<p>` instead of `<div>` for admin actions area at the bottom of the tag list to provide extra vertical margins.

HTML related fixes for the tag list page.

---

app/assets/javascripts/application.js.erb
app/assets/stylesheets/application.css.erb
app/views/stories/_listdetail.html.erb

This PR fixes the incorrect dropdown menu location for the archive button.
Both dropdown menus for the flag and dropdown buttons should work well after this fix:

Fix incorrect dropdown menu location for the archive button

---

app/assets/javascripts/application.js.erb

This is an easy fix just changing a "getAttribute" to a .value as the former only looks at the state in which it was created, not the current state.
I'm sorry that the bug crept back into the code.
I also took the opportunity to clean up some other inconsistencies. 
- When you flag a story it no longer jumps to the top of the page.

Fix duplicate url check bug, for both less & greater than 30 days

---

app/assets/stylesheets/application.css.erb
app/views/comments/_comment.html.erb
app/views/stories/_listdetail.html.erb

When the last fix for the archive/flag drop downs went through it only fixed the story related drop downs. This patch with make those same changes to the flag drop down in the comments section.

Fix bug where the comment flag dropdown is out of position.

---

app/controllers/domains_controller.rb
app/models/domain.rb
app/models/story.rb
app/views/domains/edit.html.erb
config/routes.rb
db/migrate/20220806200248_set_is_tracker_as_banned_to_domains.rb
db/migrate/20220806202153_remove_is_tracker_from_domains.rb
db/schema.rb
spec/features/submit_story_spec.rb
spec/models/domain_spec.rb
spec/requests/domains_spec.rb

Domains controller with update action and banning logic.
Removed is_tracker field from Domain model.
According this issue:
https://github.com/lobsters/lobsters/issues/1080

Domains update action and banning logic

---

app/assets/stylesheets/application.css.erb
app/views/stories/_listdetail.html.erb

In #1121 I fixed the issue that the dropdown for the archive button had a wrong position. I still spot a minor issue the archive button has no hand cursor on hover.
This PR is a quick fix to this issue.
This PR also removes the `archive_dismiss` `<label>` and associated styles since it's not needed anymore.

Fix archive button has no hand cursor on hover

---

app/models/story_repository.rb
spec/models/story_repository_spec.rb

When a story is hidden gets filtered out when loading the Active tab
Fixes [Issue#1113](https://github.com/lobsters/lobsters/issues/1133)
What was done?
- A `where.not` clause is addded to exclude the user's hidden stories

fix: filter hidden stories in active tab

---

app/assets/javascripts/application.js.erb

This fixes #1134 
Flagging a comment is a two-step process.
1. Click the "flag" link. This opens a list of reasons for the flag.
2. Click the reason
Step 2 was missing `event.preventDefault()` in the click handler.

fix unintentional scrolling when flagging a comment

---

app/views/comments/_comment.html.erb
app/views/stories/_listdetail.html.erb

These changes have zero impact on sighted users,
but give screen reader users some core elements
to key off of for navigation, level 1 headings
for stories, level 2 for comment links and level
3 for comments themselves.
The reason the comment role was not used is that
it is not yet supported by most screen readers,
but I plan to add that in another forthcoming
PR.
closes: #1123

Added aria role and levels for stories and comments

---

app/views/stories/_form.html.erb

Fixed #1161 with a simple "\&nbsp;" in the Fetch Title.
After that I could not replicate the bug at any zoom level.

Prevent a css error at various zoom levels.

---

app/assets/javascripts/application.js.erb
app/assets/stylesheets/application.css.erb
app/views/comments/_comment.html.erb

The is a new feature from request #919
When viewing comments you can now click on the "(unread)" label to scroll to the next unread label.
This was done by adding a unique id and a bit of JS to find the next label then scroll.

Feature: scroll to unread comments

---

app/assets/stylesheets/application.css.erb
app/views/stories/edit.html.erb

Issue #1157 
- Created css variables to the TomSelect tags in forms.
- Eliminated the background-image on TomSelect tags in dark mode.
- Added the story_holder div to the suggest form as it got forgotten with the original shift to TomSelect. This should stop the Tags entry from being white in dark mode.

correct dark mode tags

---

app/assets/stylesheets/application.css.erb

There's a slight spec of the background color / lack of fill in the mobile comments speech bubble when you have the page at a higher zoom level. The issue is more visible on Firefox but also happens on Chrome. 
before: 
after:

Fix spec of bg in mobile comments speech bubble

---

app/controllers/settings_controller.rb
app/views/settings/twofa_enroll.html.erb

Small change to show TOTP secret (initially hidden and revealed on click). This allows for manual entry, which is particularly useful if your 2FA is a browser extension such as bitwarden.
Preview:

Add reveal for TOTP secret for manual entry

---

app/models/story.rb
spec/models/story_spec.rb

Extends the `Story::find_similar_by_url` metod by adding a check for youtube URLs.
Handles `youtube.com`, `www.youtube.com`, `youtu.be` and `m.youtube.com` URLs
I couldn't find a official source for valid youtube video URLs, so I've based my research on [this](https://gist.github.com/rodrigoborgesdeoliveira/987683cfbfcc8d800192da1e73adc486) gist.
Edit: Forgot to mention that it partially addresses #1171, I'll address the video tag part later(prolly Friday)

Add youtube duplicate detection

---

app/views/settings/index.html.erb

Settings that require a Pushover subscription are rendered before the button to setup the Pushover integration, so the labels "above" and "below" should be swapped.

Update messaging for Pushover settings

---

app/assets/javascripts/application.js.erb

Minor typo I came across when I accidentally deleted my comment.
Previously: `Are uou sure you want to undelete this comment?`
Now: `Are you sure you want to undelete this comment?`

typo fix for undeleting a comment alert

---

app/views/search/index.html.erb

Without this, all of the pagination buttons link to the current page.
Before:
After:

search: Use the page in pagination links

---

README.md

Update git clone url to the preferred github, git user style.

Fix git clone URL

---

app/controllers/search_controller.rb
app/models/search.rb

This PR is just for fixing the latest merge that introduces a failing
test.
When initializing a new Search model it has some default values,
especially the `results_count` one.
https://github.com/JuanVqz/lobsters/blob/5338e5a4b335b94337636a59b7bbc83529dfce81/app/models/search.rb#L42
When doing Search.new({}, nil) in the `ignore_searx` method
https://github.com/JuanVqz/lobsters/blob/5338e5a4b335b94337636a59b7bbc83529dfce81/app/controllers/search_controller.rb#L30
It takes the` -1` value by default which in this if/else statement
https://github.com/JuanVqz/lobsters/blob/5338e5a4b335b94337636a59b7bbc83529dfce81/app/views/search/index.html.erb#L40
is rendering this else block
https://github.com/JuanVqz/lobsters/blob/5338e5a4b335b94337636a59b7bbc83529dfce81/app/views/search/index.html.erb#L157- …

Fix search failing test

---

app/assets/stylesheets/application.css.erb
app/views/moderations/_table.html.erb

Closes #1231.
Lines containing a long URL, for instance, would cause the text to overflow its content box.
In the original issue [it was suggested][1] to use `word-break: break-word;` but [this property value is considered to be deprecated][2].
The fix was specifically applied to the `Action` column in order to not break the username in the `Moderator` column. 
P.s.: I'm not a Frontend Developer, so please let me know if this has to be done in a completely different way.
[1]: https://github.com/lobsters/lobsters/issues/1231#issuecomment-1858890718
[2]: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

Fix long lines in moderation action description

---

app/views/stories/_form_errors.html.erb
app/views/stories/_similar.html.erb
spec/requests/stories_spec.rb

Closes #1215.
The approach consists in not filtering out merged stories (avoiding the `unmerged` filter) and showing them in the returned HTML.
Please let me know if should we do it differently.

Show merged stories on duplicate submission

---

app/views/layouts/application.html.erb
public/opensearch.xml

Mainly allows Firefox users to add Lobsters as a search engine.
See [the specifications](https://github.com/dewitt/opensearch) and [MDN](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) for more info.

Add OpenSearch description document

---

app/views/home/rss.erb

When I'm browsing lobste.rs it's helpful to see the domain without hovering over the link. This adds that ability to the RSS field. It saves space by removing the email-address-like part of the username.

Add domain to RSS author

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/story.rb
config/initializers/prosopite.rb

https://github.com/lobsters/lobsters/issues/1252

Added gem prosopite

---

app/assets/stylesheets/application.css.erb

Noticed this small thing while browsing lobste.rs on Firefox on my phone today.

Fix unnecessary tag wrapping in Firefox.

---

Gemfile
Gemfile.lock
app/models/comment.rb
app/models/domain.rb
app/models/hat.rb
app/models/invitation_request.rb
app/models/mastodon_app.rb
app/models/message.rb
app/models/moderation.rb
app/models/read_ribbon.rb
app/models/story.rb
app/models/story_text.rb
app/models/suggested_title.rb
app/models/tag.rb
app/models/user.rb
app/models/vote.rb
db/migrate/20240606084311_add_missing_null_checks.rb
db/migrate/20240608224626_add_indexes_on_foreign_keys.rb
db/schema.rb
spec/models/story_spec.rb

First pass at making updates recommended by `database_consistency` and `active_record_doctor` as per issue #1281 
These are the straight forward updates. There's some "non-standard" stuff in the schema that's resulting tricky fixes and  false positives. I think this PR is boarding on too big so I'll tackle the rest in another PR.
Note: There is a possibility that the migration that adds NOT NULL constraints might fail if those columns have NULL in them.

Database consistency fixes

---

.github/workflows/check.yml
app/helpers/application_helper.rb
app/models/moderation.rb
app/models/story.rb
spec/extras/bitpacking_spec.rb
spec/models/story_spec.rb

As you may know, Ruby 4 is likely to make frozen string literals the default, in that context I wanted to see how much work would be needed for a relatively classic app.
Turns out it wasn't much work for lobsters.
I'm not particularly asking for this to be merged, just submitting it in case you'd want this change. It would allow you to run ruby with `--enable-frozen-string-literal` in production, which should reduce the GC pressure a bit (but don't expect crazy numbers).

Make the application compatible with `--enable-frozen-string-literal`

---

app/views/search/index.html.erb

`tag:meta` in the search page is inconsistent:
Replaced a mismatched `<code>` tag to fix the inconsistency.

Fix mismatched tags on search page

---

app/assets/stylesheets/application.css.erb

System colors are deprecated in CSS3, and as such the Highlight and HighlightText keywords don't function properly on Chrome. 
https://www.w3.org/TR/CSS2/ui.html#system-colors
Removing these lines makes browsers just use the defaults, which looks more similar (albeit not the same) across the board. Don't know if you want to hard code in a selection color value, some users might want to define their own.

Fixed text highlight color

---

config/puma.rb

Ref: https://github.com/Shopify/ruby/issues/556#issuecomment-2211754838
Note: This is totally untested
`out_of_band` is invoke when a request finishes and no other thread is busy. So theorically it may never be invoked if the worker is under constant load, but I'm hoping it will eventually.
The idea here is to wait for the number of live object to go over some threshold we found in the GC stqats we dumped previously, and when it's reached we dump the heap a second time.
By comparing it with the heap that was dumped after boot, we should be able to figure out what extra objects are being retained after the worker ages.

Dump heap after boot and after bloat

---

app/models/keystore.rb

`#pick` is a short-hand for `relation.limit(1).pluck(*column_names).first`, hence the `limit` clause is redundant here.

Remove redundant limit from #pick call

---

.github/workflows/check.yml
Gemfile.lock

Might as well run them concurrently, it's faster and allow to see directly from the GitHub PR what the failure is about.

Split CI steps in multiple jobs

---

app/assets/javascripts/application.js.erb
app/views/stories/show.html.erb

I couldn't activate the "unread" link, that scrolls to the first unread comment, because it lacked a role. Now it has a role.
I also took the opportunity to check the "reduced motion" preference to determine scrolling behavior.

Accessibility improvements for "unread" feature

---

app/models/story.rb
app/views/comments/index.rss.erb
app/views/home/rss.erb
extras/html_encoder.rb
spec/extras/html_encoder_spec.rb

While profiling the lobsters benchmark in the yjit-bench suite I noticed a weird 0.8% of time spent in `instance_eval`.
Tracking it down, it's coming from the htmlentities gem, when calling `HTMLEntities.new` it generates code on the fly based on the options.
~~As such you aren't meant to instantiate a new one every time, but have a single global object somewhere.~~ Actually seems like you are, that gems just bad.
Otherwise this constant code generation is wasting performance for now reason, and potentially use YJIT executable memory if called enough.

Avoid continiously instantiating HTMLEntities

---

README.md
bin/setup

Hi. I was setting up the codebase this morning and struggled a bit as I don't have a lot of mysql experience. I took some steps to get it working, and then updated some README/code:
* Add instructions to start the `mysql` server
* Add instructions to set the root password to match `database.yml.sample`
* Use the `db:setup` command in `bin/setup`. It does the same thing and will be a little faster since it doesn't have to load the rails app for three commands.
Totally open to feedback if there's a more idiomatic way to set up local mariadb.

Improve setup

---

app/models/story.rb

PR #1320 changed this from HTMLEntities.new.decode to HtmlEncoder.encode which does the opposite of what it used to do.
Should fix #1328

Story: description_or_story_text should return plaintext

---

app/assets/stylesheets/application.css.erb

Issue #1282
Checked the issue & came to following conclusion
Updated the current print-specific CSS
Defined rules to hide the comment_folder and comment forms when a user prints a page.
Looks fine to me for now will update if more fixes are needed

Issue #1282 - Updating application.css.erb rule to hide folders

---

app/views/home/index.html.erb

This might be more clear.
There's a [discussion thread](https://lobste.rs/s/nsdzkf/suggestion_change_archive_link_text)
Perhaps "mirrors" or "archives" would be better, but I figured the "obvious improvement" comment was a sign to go ahead rather than do some bikeshedding.

Change "archive" link to "caches"

---

app/models/story.rb
app/views/home/index.html.erb
app/views/search/index.html.erb
app/views/stories/_listdetail.html.erb
spec/models/story_spec.rb

This is a late PR after the issue submitted on #1321.
The changes are described on the commit messages. Basically:
* The first commit makes the story preview action not forget the story tags by making `Story#tags_a` work on preview stories (i.e. unsaved). It fixes #1264.
* The second commit makes the story preview show the submitted tags.
I'm not too keen on the approach taken on the 2nd commit. I wish `Story#tags` would Just Work™ on unsaved stories, but alas, it doesn't. Suggestions are welcomed!
The two commits are independent from each other. I left them this way if you prefer to apply the first one without the questionable approach of the second one :)

Remember tags when previewing a story

---

app/assets/stylesheets/application.css.erb

Fixes #1333.
Tested with the home list page and a story page:
Before: Landscape exhibits the bug, in which some fonts are the same as portrait and some are enlarged.
After: Landscape keeps the same font sizes as portrait.
Portrait font sizes were unaffected by the change.
Before:
After:
Curiously, I didn't reproduce today the enlarged tags on the story page that I saw when I wrote up the issue.

Fix #1333 Some but not all text changes size when rotating Mobile Safari to landscape

---

app/views/stories/_form.html.erb
app/views/stories/_form_errors.html.erb

Fix #1334 
Currently for an already submitted story when a different user tries to do a suggestion (click on `suggest` link) it show the `is_resubmit?` form as well as the `similar_stories.any?` form, this forms are intended when a user is submitting a story.
Current behavior:
- test user with original story:
- renna_collins with a resubmitted story 
- will_shannon clicking "suggest" (different user)
New behavior:
- will_shannon clicking "suggest" (different user)
- long_armstrong clicking "suggest" (different user)

Issue #1334 Fix validation for resubmitted story form

---

app/assets/javascripts/application.js.erb
app/controllers/stories_controller.rb
app/models/story.rb
app/views/stories/_listdetail.html.erb
config/routes.rb
spec/features/story_spec.rb
spec/requests/stories_spec.rb

Fix #1331 
Allow stories to be disowned individually
Validate:

Issue #1331 Implement story disowning

---

Gemfile.lock
app/models/message.rb
spec/factories/message.rb
spec/models/message_spec.rb

Fix #1353 
I was able to reproduce the issue but just for `messages` and the only way i was able to reproduce it was deleting the record through the console/database.
My hunch is there was a directly delete of the record for some reason, or for another strange reason the `after_save :update_unread_counts` hook was not triggered.
- added `before_destroy` to make sure recipient gets `unread_messages_count` updated

Issue #1353 Fix unread counts for message destroy

---

app/models/story.rb
extras/utils.rb
spec/extras/normalize_url_spec.rb
spec/models/story_spec.rb

Fix #1339 
The url normalizing methods ( Utils.Normalize and Story.set_domain_and_origin ) have been updated in order to be more flexible with domains names as www10.org .
Current behavior : 
www10.org is displayed as org in a story
New behavior :
www10.org is displayed and classic urls are still displayed correctly for instance www.google.com is displayed google.com

Issue #1339 Utils.normalize(url) mishandles www10.org 

---

config/application.rb
config/initializers/00_zeitwerk.rb

Hi :) 
Fixes https://github.com/lobsters/lobsters/issues/1246
According to documentation, adding `extras` folder to `autoload_path` [here](https://github.com/lobsters/lobsters/issues/1246) is the right way to make every file in it autoloaded.
However it looks like we also manually `require` all files in this folder [here](https://github.com/lobsters/lobsters/blob/master/config/initializers/00_zeitwerk.rb#L14) which probably (I don't actually know) messes up with RoR reload mechanisms. 
Hope this small fix can make hacking on lobsters a more pleasurable experience. 
Let me know what do you think. 
P.S.
Should we add that `lib` folder to `autoload_path` in the `config/application.rb` similarly to how `extras` folder is added? I guess the whole `each` block can be removed then. Apparently …

Fix reloading for extras folder

---

.custom_cops.yml
.standard.yml
config/application.rb
lib/custom_cops/inherits_moderator_controller.rb

All controllers in the `app/controllers/mod/` directory should inherit from `Mod::ModeratorController`
resolves #1393
Note:
The cops are located in the `.lib/custom_cops/` directory, which I've added to the ignore list of `config.autolod_libs`. If my understanding of [config.autoload_libs(ignore:)](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#config-autoload-lib-ignore) is correct, this should prevent this directory from being loaded when the application runs (in any environment).
If your editor is configured with standardrb integration, the code in `.lib/custom_cops/` will load and will run for ruby files in the `app/controllers/mod/` directory.

Add cop to standardrb to enforce Mod::ModeratorController #1393

---

.github/workflows/check.yml

We might see a speedup in tests if hot code is JIT'd. Costs us very little to figure that out by opening a PR and letting the specs run.

Enable YJIT in the test suite

---

app/assets/javascripts/application.js.erb

When the user clicks 'Fetch Title', in addition to filling in the title field, also automatically set the value of the URL field. This is primarily because servers often redirect to a canonicalized or secure (HTTPS) version of a URL if someone requests an alternate or insecure (HTTP) version.
With this change, we use the URL that the server prefers for the document.

Update URL when fetching title

---

app/controllers/moderations_controller.rb
app/views/moderations/index.html.erb
config/brakeman.ignore
spec/requests/moderations_spec.rb

Fixes #1425 
The params in the moderations index are used to generate the pagination links so we keep the same filters on the next/previous page. Currently on master we're forwarding *all* `params` whether they're used by the page or not. This breaks if `:action` (or `:controller`) are injected as parameters, due to Rails internals. As a rule of thumb we shouldn't be generating links containing injected content from users/previous URLs, but generating a link only with the whitelisted params we expect to be in the URL.
Brakeman was upset with our construction of SQL conditional from a string, even though we controlled the input from hash keys. Rewrite it slightly to generate the same SQL (minus some superfluous brackets) but using the power of the DSL to escape anything untoward if it …

Fix 500 in moderations pagination

---

app/views/stats/index.html.erb

fixes #1420 by replacing hardcoded values with `var()` and adding a few more overrides like axis label colours
**Light mode** (no change)
**Dark mode** (actually dark)

fix /stats styles to support dark mode

---

Gemfile
Gemfile.lock
config/environments/production.rb
extras/gvl_instrumentation.rb

In response to https://byroot.github.io/ruby/performance/2025/01/23/the-mythical-io-bound-rails-app.html @pushcx kindly offered to instrument the actual IO ration on lobster production environment.
This PR does exactly that using the `gvl_timing` gem, inside a custom middleware mounted about as high as possible in the stack.
On my local environment it produces the following logs:
```
[GVL] io_percent=9.1, run_ms=30.57, idle_ms=2.95, stall_ms=0.03, gc_ms=0.0, path=/active
```
Perhaps you'd prefer if these were integrated in the main logs? I'm not familiar with your current log infra, but if you point me to it, I can probably hook them off.

Add instrumentation of the GVL

---

app/assets/stylesheets/application.css

- Since the `light-dark` function can only take color values, the usage is corrected by applying opacity through an inner `rgba` call.
- Use `color-mix` to apply opacity instead of `rgba` where practical.
- Redundant `--palette-*` variables are removed.
This should fix #1445.

reorganize color variables (fix #1445)

---

app/controllers/moderations_controller.rb
app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

this should fix #1433 
I put the calculation in a helper, just so I could write an easy test for it.
There are several other controllers that use pagination (any that define a `*_PER_PAGE` constant) but none count the total number of pages, so don't seem to be affected by this bug.

fix count of pages in ModerationsController #1433

---

app/assets/stylesheets/application.css
app/assets/stylesheets/dark-contrast.css
app/assets/stylesheets/dark.css
app/assets/stylesheets/light-contrast.css
app/assets/stylesheets/light.css
app/assets/stylesheets/system-contrast.css
app/assets/stylesheets/system.css
app/controllers/settings_controller.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/settings/index.html.erb

This PR builds on #1453 and adds a user setting that enables increased contrast in the current color scheme.
This functionality was recently brought up after a bug (#1445) turned the text black on white (and vice versa in dark mode), and multiple users in [the thread about it](https://lobste.rs/s/o2hhjc/what_happened_text_colour) expressed support for the inadvertent change.
Feedback on the suggested colors and nuances is more than welcome.

Color schemes with increased contrast

---

Gemfile
Gemfile.lock
config/initializers/scenic.rb
db/cache_schema.rb
db/schema.rb

#1458 exposes the fact we can't run `bin/rails db:schema:dump` successfully on master. We can dump the primary database (MySQL), but we run into an error dumping the cache database (SQLite). This is because the Scenic MySQL adapter runs queries against the SQLite database it doesn't understand so errors out.
Attempt to patch this quickly by adding a proxy object that picks between both depending on what the current connection to a database is.
This works for `bin/rails db:schema:dump`, but I've not tested the app otherwise. It may well break in other places!

Proxy Scenic to correct adapter with multiple databases

---

app/views/about/chat.html.erb

This file seems unparsed by a Markdown parser.

Replace Markdown links with HTML links

---

app/views/comments/_threads.html.erb

The `<li class="comment_subtree">` tag of the first comment in each comment tree was accidentally left unclosed: it doesn't have a matching  `</li>` tag, but all its child comments do. We should fix this because when a `<li>` element has a missing end tag, HTML5 infers where to place the end tag using heuristics. The heuristics may fail at times, leading to subtle UI bugs on pages that display nested trees of comments (such as stories and user profiles).
We can use a [closing tag checker](https://www.aliciaramirez.com/closing-tags-checker/) to verify that this commit closes these open tags.
(I think github deleted the old pull request because my throwaway email made me look like a bot account. Sorry about the confusion.)

Close the top-level comment tags

---

app/controllers/home_controller.rb
app/views/home/index.html.erb
spec/features/newest_spec.rb

#1394 Fixed second part of issue related to `last_read_newest` and` Last Read` marker.

Fix 'last_read_newest' and 'Last Read' marker 

---

app/controllers/comments_controller.rb
app/javascript/application.js
app/views/comments/_commentbox.html.erb

The first commit here fixes b122213f2b99c922fd86fc50cf5c1a7cb19d0eb4 to correctly render the edit box with JavaScript enabled. Using `fetch` doesn't set the `X-Requested-By` header, so `request.xhr?` will return false. Instead of adding this header manually I've switched to using `fetchWithCSRF` which already added it, for reasons I'll explain at the end.
The second commit fixes #1487 by choosing to either send a redirect or a partial in response to an update request. Note that the fetch API does not allow introspecting on 302 responses, either omitting them entirely or (with `redirect: 'manual'`) redacting them. Therefore, I introduced an `X-Location` header which can be sent in any response to be handled as a redirect by the JavaScript. At present this is sent in another code path, …

Fix comment editing to work with and without JS

---

app/javascript/application.js

This should resolve another bug from #1488. Rather than always inserting the replacement comment in the top-level, try and find its immediate parent first. Note we do this query before removing the form, otherwise its position in the DOM is lost.

Replace edited replies in their correct subtree

---

app/assets/stylesheets/application.css

With a regular hyphen (U+002D) the `[-]` marker uses slightly less space than `[+]` in most standard fonts, resulting in unsatisfying aesthetics especially when toggling the state.
Instead, use a minus character that has the same with as the plus character.
Before
After
(I'm not sure which variant is preferred - encoding the character as UTF-8 and declaring the use of UTF-8 as in this PR or the slightly more conservative solution of escaping the string. Happy to switch it.)

Use a minus sign (U+2212) instead of hyphen to collapse

---

app/views/users/show.html.erb

It took me literally completely finishing a bug report to realize that this text meant stories marked as "I am the author of the story at this URL", _not_, stories submitted by you (i.e. "_submissions_ authored by you").
So, try and make this text a bit more unambiguous.
This wording probably isn't the best. Feel free to bikeshed and feel free to force-push to my branch. I just went to file an (alternate) issue and then realized it was super easy to just at least propose a strawman.
This was a drive-by GitHub web UI patch and I did not test it at all. It's trivial so I'm assuming CI will take care of it.

Clarify participation/self-promo text wording

---

Makefile

I try follow the steps for docker in [`setup_with_docker.md`](https://github.com/lobsters/lobsters/blob/master/docs/setup_with_docker.md) and I found the following error when I try to build:
```bash
$  make docker-serve
export RUBY_VERSION=`cat .ruby-version`
docker compose up --build
WARN[0000] The "RUBY_VERSION" variable is not set. Defaulting to a blank string.
Compose now can delegate build to bake for better performances
Just set COMPOSE_BAKE=true
[+] Building 0.0s (1/1) FINISHED                                                    docker:default
=> [app internal] load build definition from Dockerfile.dev                                  0.0s
=> => transferring dockerfile: 616B                                                          0.0s
=> WARN: InvalidDefaultArgInFrom: Default value …
```

fix make docker-server

---

app/views/stories/_singledetail.html.erb

The first commit fixes displaying a duplicated comment count for unmerged stories (one a sum of all the merged stories, one the comment count on the story itself). We still render only a total comment count for merged stories.
The second commit fixes some unclosed control flow that was skipping more of the template for logged-out users than intended. I've checked this over a few times and I think it's correct now, but it's probably worth another skim over.
Closes #1502

Fix display of story _singledetail

---

app/controllers/mod_controller.rb

Ran into this while working on #1508
```
N+1 queries detected:
SELECT `categories`.* FROM `categories` WHERE `categories`.`id` = 11 LIMIT 1 /*action='index',controller='mod'*/
SELECT `categories`.* FROM `categories` WHERE `categories`.`id` = 10 LIMIT 1 /*action='index',controller='mod'*/
SELECT `categories`.* FROM `categories` WHERE `categories`.`id` = 9 LIMIT 1 /*action='index',controller='mod'*/
SELECT `categories`.* FROM `categories` WHERE `categories`.`id` = 8 LIMIT 1 /*action='index',controller='mod'*/
SELECT `categories`.* FROM `categories` WHERE `categories`.`id` = 7 LIMIT 1 /*action='index',controller='mod'*/
Call stack:
app/views/moderations/_table.html.erb:29
app/views/moderations/_table.html.erb:8
app/views/mod/index.html.erb:4
app/controllers/application_controller.rb:143:in …
```

Fix 1+n query on /mod

---

app/views/about/about.html.erb

Small followup to https://github.com/lobsters/lobsters/commit/240647f403787684e3e1c8c88e528a0a9dc3f941 - there were two other instances of this broken link format on the page

fix #1506 more bad links to modlog

---

lib/tasks/fake_data.rake

I've found having a variety of vote counts useful while working on layout, but they weren't generated as part of `fake_data`.
This is by far the slowest part of the fake data generation, I suspect because of the repeated sampling of users. Perhaps bulk inserting votes or only processing a subset of stories/comments would be viable.

Add fake story and comment upvotes in fake_data

---

.github/workflows/check.yml
.github/workflows/stale.yml

This commit does following
- bump mariadb to be in sync with the latest setup on prod to 10.11.11
- update all actions/checkout to v4
- update the state action to v9 (latest stable)
- Also, implement a cocurrency check to cancel in progress CI runs when a new commit is pushed to cancel the old run.

feat: update github actions setup

---

app/views/about/about.html.erb

Before, the "trivia" section was considered a list item of "technical features" and indented accordingly.

Close <ul>s appropriately on /about

---

app/assets/stylesheets/application.css

I forgot that the nav's `grid-column: 1 / -1` was load-bearing, in that the last column on mobile is some right padding. I've made it more clear what's going on there.

Allow nav to spill into the right padding on mobile

---

app/views/comments/_postedreply.html.erb
app/views/comments/index.html.erb
app/views/replies/show.html.erb

In several places, we fake a thread by manually creating an empty list of children. Add the `<div>` workaround in those places so the styling can apply consistently.
This is yet another commit to revert when we solve this properly. On the bright side, that should be all the more satisfying.

Add the <div> workaround everywhere comments are rendered

---

app/views/users/show.html.erb

This fixes the regression in  c4a68b9d4c9547e38350a9027262e5e341b7f7c7 (see show.html.erb:18) that rendered style attribute outside of tag.

Fix styling of "Banned user" on users/show

---

app/assets/stylesheets/application.css

Originally noticed this because it uses the CSS nested selector: a more recent addition. The colour is the same as applied without :hover, and as far as I can see there is no "disable" class, so I don't believe we need this block.

Remove unused nested selector rules

---

app/helpers/application_helper.rb

Use `<time>` instead of `<span>` for these labels, to ensure the times are machine-readable. This doesn't affect the text that appears when a user hovers, though that has a different format than the machine-readable portion.

Use the <time> element for display how_long_ago_labels

---

app/assets/stylesheets/application.css
app/views/messages/_form.html.erb
app/views/messages/index.html.erb
app/views/messages/show.html.erb

This was pretty smooth, requiring only a few changes to the stylesheet itself. Hopefully as this work goes on it'll just be a matter of putting the appropriate classes in the appropriate places.
The table for the list of messages is still laid out with manual percentage widths. This might be worth changing at some point, but for now I'm aiming to standardise the common page structures, rather than the unique elements.
This is work towards #1279 
<details>
<summary>Some rather uninteresting screenshots</summary>
</details>

Lay out the pages for private messages using CSS Grid

---

app/views/about/about.html.erb

This makes things line up a bit nicer, though sadly for me the aesthetic center of the lobster emoji still doesn't match that of the disc markers.
Before:
After:

Stop inserting the custom lobster emoji list marker manually

---

db/migrate/20250521131204_temporal_tokens.rb

If a tag isn't used on any stories, created_at and updated_at would be null, which would error when the NOT NULL constraints are added.
(marked @pushcx as author, the patch was originally in non-machine-readable form over IRC)
Closes #1583

Fall back to current time for tag created_at and updated_at

---

app/jobs/fill_flagged_cache_job.rb
config/recurring.yml
script/fill_flagged_cache.rb

Howdy! This PR resolves one small chunk of issue #1548. I start by porting only the `fill_flagged_cache` job, because my Rails is a tad rusty and I wanted to make sure I'm doin' it right before I tackle a larger chunk.
See the `lobsters-ansible` sister PR for cleanup of the cron job: lobsters/lobsters-ansible#89
Wasn't sure what order you'd prefer to ship the ActiveJob vs. the cron removal. I figure if you shipped the ActiveJob first, `fill_flagged_cache` would run twice for a while and I wasn't sure if it was idempotent. So I structured this as though the cron job would be taken offline first in the other PR, then this would ship second. Let me know if this is incorrect and I can restructure accordingly.

Port `fill_flagged_cache` to an ActiveJob

---

app/javascript/application.js
app/views/stories/_form.html.erb

I don't think I explained this very well during office hours, but it turns out TomSelect uses the `dataset` of the `<option>`s, which [converts kebab-case names from the HTML into camelCase names in JS](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset#in_javascript). You have to use the latter to refer to attributes for sorting.
I don't think the prior `data-value` sort was working before, but because the elements were in the right order to begin with, it didn't matter.
Closes #1595

Sort 'vibecoding' above 'ai' in TomSelect

---

config/sitemap.rb

Fix this issue over here - https://github.com/lobsters/lobsters/issues/1496
It's not my first PR here so my apologies for stealing `good first issue` from other people. I just wanted to generate a sitemap locally and noticed this issue which I then found already created. 
The issue was introduced here - https://github.com/lobsters/lobsters/commit/2332d2802254af5d77ff4808a69b42523fdae4c3 
I'm unable to find reasoning behind this change and I can't find proofs that `create!` has ever existed in `sitemap_generator` gem. Probably that `!` was just introduced by accident. 
Hope it's gonna fix the cronjob you have in prod.

Fix sitemap generation

---

app/controllers/home_controller.rb
app/models/story.rb
app/models/story_repository.rb
spec/controllers/home_controller_spec.rb
spec/models/story_spec.rb

This the first part of https://github.com/lobsters/lobsters/issues/1523: the `hidden` scope. I'd like to move by small steps, so one scope per PR is good for me. 
Please, let me know if this approach is not acceptable.

Refactor story repository (Part 1)

---

app/jobs/refresh_sitemap_job.rb
config/recurring.yml

This PR does another chunk of #1548: the sitemap job. A sister PR, lobsters/lobsters-ansible#90, cleans up the cron.

Port over the sitemap refresh cron job to an ActiveJob

---

app/controllers/home_controller.rb
app/models/story.rb
app/models/story_repository.rb
spec/models/story_spec.rb

https://github.com/lobsters/lobsters/issues/1523
Move `newest` method from the repository to Story model as a scope.

Refactor Story Repository: newest method

---

app/helpers/application_helper.rb

This fixes an issue on /login on mobile where the login link appears in the navbar twice, because `current_page` beats out `corner` in the first list of links.

Don't ignore other classes on current_page in link_to_different_page

---

app/controllers/home_controller.rb
config/routes.rb
spec/controllers/home_controller_spec.rb
spec/routing/home_spec.rb

Fixes #1602, and adds additional functionality for the top feeds because its easier to do that than only allow the `/top/:length/rss` feeds.
Technically `/top/rss` isn't a valid feed anymore, but it redirects to `/top/1w/rss` which is now a valid feed and any well behaved feed reader should handle that. The upside is you can subscribe to a feed of any length you want now, eg `/top/1m/rss` or `/top/3d/rss`.
Closes #1606 I think, one of the tests is incorrect and the other is better tested in the routing/controller specs here.

Reinstate `/top/rss` and allow RSS for any `/top/…/rss` path

---

app/assets/stylesheets/application.css
app/javascript/application.js
app/views/comments/_commentbox.html.erb
app/views/global/_markdownhelp.html.erb
app/views/layouts/application.html.erb
app/views/mod/stories/edit.html.erb
app/views/settings/index.html.erb
app/views/signup/invited.html.erb
app/views/stories/edit.html.erb
app/views/stories/new.html.erb

Switch to using a `<details>` element for this help, so it doesn't require JavaScript. I elected for this over the checkbox hack as it's more semantically appropriate.
The look of the dropdown has changed (though I matched the font size so it remains less distracting). Personally, I like the new look as it more clearly communicates what's going to happen, and leans on the native browser rendering, in line with the rest of the site. I'm not opposed to trying to more closely match the existing design, however.

Stop using JavaScript for Markdown help

---

app/assets/stylesheets/application.css

I usually don't like fixing CSS bugs with `!important`, but it seems to do the trick here:
| Before | After |
| --- | --- |
| ![IMG_7648](https://github.com/user-attachments/assets/7287f6e5-f0a5-4a1b-ac08-0f03a21d74e2) | ![IMG_7649](https://github.com/user-attachments/assets/2cbb69cc-8820-4bd9-b183-fd1c54d8e34a) |
Feel free to close this if you can think of another way of fixing this!
/cc @veqqq

Fix upvote hover state on iOS

---

app/assets/stylesheets/application.css
app/controllers/notifications_controller.rb
app/jobs/notify_comment_job.rb
app/jobs/notify_message_job.rb
app/models/comment.rb
app/models/message.rb
app/models/notification.rb
app/models/user.rb
app/views/comments/_comment.html.erb
app/views/comments/_threads.html.erb
app/views/messages/_subnav.html.erb
app/views/notifications/_message.html.erb
app/views/notifications/all.html.erb
config/routes.rb
db/migrate/20250628172500_create_notifications.rb
db/schema.rb
lib/tasks/backfill_notifications.rake
spec/factories/hidden_story.rb
spec/factories/notification.rb
spec/jobs/notify_comment_job_spec.rb
spec/jobs/notify_message_job_spec.rb
spec/models/notification_spec.rb

Work for https://github.com/lobsters/lobsters/issues/1076
Currently notifications are isolated from the other parts of the site like unread messages/unread comments because I'm not yet sure what the migration / integration will look like so I'm going to leave it open for now. This is why you might see "1" unread at the top, but the screenshot has 5 unread notifications.
For messages, the bold text under the byline is the subject, to differentiate it from the body.
Clicking on unread works as expected for both messages and comments.
Added pagination to all notifications, but not the unread, since we clear them out after clicking on the tab.
I might have found a bug while taking some of the pagination code from the replies. The replies controller limits to …

add support for notifications 

---

config/initializers/session_store.rb

Was chatting with @pushcx during lobste.rs office hours and discussing options, while yak shaving development improvements; one of the options was disqualified for the desire to protect user accounts. This change hardens the settings for session cookies, restricting the surfaces that are able to access these cookies.
So, technically, this patch is just a guess, because either I'm not searching correctly, or there doesn't appear to be docs describing this exact behavior. https://api.rubyonrails.org/v5.2.1/classes/ActionDispatch/Session/CookieStore.html is the closest I was able to find, but the docs lack the behavior confirmation I'd hope to see. I was able to find tests that I think enforce this behavior, but I don't wanna assert confidence yet, not until I see the cookie attrib set …

harden session cookies making same_site strict and httponly

---

config/routes.rb
spec/routing/home_spec.rb

The change in #1629 caused the previous and next page links on the Top Stories pages to link to the RSS pages instead.
I think it's because the new top RSS route matches before the regular top HTML route matches. I fixed this by swapping the order of the top page routes and adding a more specific `/top/rss` route for the case where that's requested. I also added a test to make sure the URL generated for the previous and next page links is correct.
I rarely write Ruby and have never contributed to a Rails codebase so please let me know if my approach is idiomatic.

Fix top stories page linking to RSS

---

app/models/story.rb

When submitting a story with Japanese title in local dev env, met the validation error.
The background is I'm planning to run a non-English speaking site using Lobsters code base, when exploring the features the code base provides, I was stopped at submitting stories.

fix(story): check for ascii only titles

---

Gemfile.lock
app/jobs/restic_job.rb
config/database.yml.sample
config/environments/production.rb
config/initializers/lograge.rb
config/storage.yml

This PR is to replace all hardcoded paths outside of hatchbox & script dirs.
Although there is one more case in `config/puma.rb`,  it can be bypassed by using `PIDFILE` env variable.(or maybe we can just remove the path there for production env, let target deployment set the PIDFILE explicitly) 
https://github.com/lobsters/lobsters/blob/d6194605f17fd2354f524077f9875ec2ce1fc26c/config/puma.rb#L30
Background: https://github.com/lobsters/lobsters/pull/1667#issuecomment-3080262996

fix: replace hardcoded paths outside hatchbox dir

---

app/controllers/application_controller.rb
docs/setup_with_docker.md
spec/features/homepage_spec.rb

**Issue**: https://github.com/lobsters/lobsters/issues/1594 
**To do:**

Remove unknown cookies and end empty session 1594

---

app/controllers/moderations_controller.rb
spec/requests/moderations_spec.rb

This is not urgent as I assume you will never run into this error on the actual site. 
I setup a newer docker instance and went to the moderation log. I removed all the filters except the user filter. http://localhost:3000/moderations?moderator=%28All%29&what%5Busers%5D=users
Docker output:
```
lobsters-app-1  | Started GET "/moderations?moderator=%28All%29&what%5Busers%5D=users" for 172.20.0.1 at 2025-07-22 01:57:17 +0000
lobsters-app-1  | Processing by ModerationsController#index as HTML
lobsters-app-1  |   Parameters: {"moderator" => "(All)", "what" => {"users" => "users"}}
lobsters-app-1  |   User Load (1.1ms)  SELECT `users`.* FROM `users` WHERE `users`.`session_token` = 'JmLib2xPwmGLT1QpGsVY1bgx8jGGIs1P4efuxPacR9OENC97p0rADg0dnTEh' LIMIT 1 /*action='index',controller='moderations'*/ …
```

Fix error on moderations filter with no results

---

app/views/stories/_singledetail.html.erb

When testing the hide/unhide feature locally, i found the "hidden by" info is displayed after "save/unsave" section, ideally it should come after the "hide/unhide" section?
Since i don't have an account on lobste.rs, i'm not sure if current behaviour is expected or not. if it's on purpose please feel free to close the PR.
---
Before:
After:

fix: hidden by info should come after hide link

---

app/models/mod_note.rb
app/views/stories/new.html.erb
spec/features/submit_story_spec.rb

Found a bug(creating duplicate mod notes) when a new user submit a story from a unseen domain.

fix(mod_note): prevent creating duplicate mod note when preview

---

app/assets/stylesheets/application.css

Fix #1680 
That bug i think was introduced by #1645, previously there is a logic for mobile device to explicitly clear the highlight color, however that logic was ignored by the `!important`.
This PR reverts the change made in #1645 and provides another solution to fix the original issue described in #1645

fix(unvote): clear arrow highlight after unvoting

---

app/views/global/_markdownhelp.html.erb

Technically it is markdown, but its part of markup that lobste.rs supports.

markdown help: Document the syntax to refer to users
