- app/assets/stylesheets/application.css
Not sure if it was on purpose or not, I think it looks better centered though.
> Off-centered #header was driving me insane.

- README.md
- db/seeds.rb
created a seeds file to populate initial data.
> added seed to populate initial data.

- app/models/story.rb
Aw heck, just do a PR for the comment I put in at https://github.com/jcs/lobsters/commit/09f65774c200049e89827880023ed233bb7d3cf2
> Truncate at end-of-string, not at every EOL

- app/assets/javascripts/application.js.erb
- app/assets/stylesheets/application.css
- app/views/comments/_comment.html.erb
Allows guests and users with javascript disabled to fold comments.
> Implement comment folding in pure css

- app/controllers/home_controller.rb
Knocked off the rescues in about and privacy.
> Don't 500 if someone hasn't added a chat template

- app/assets/stylesheets/select2.css.erb
Bugfix to generate asset paths for the select2.png.
> Use asset_path in select2 image URLs

- app/views/layouts/application.html.erb
- config/locales/en.yml
- config/locales/fr.yml
I18n support for layout/application.html view
- app/views/layouts/application.html.erb : i18n support for layout/application.html view
- config/locales/en.yml : 18n english strings for layout/application.html
- config/locales/fr.yml : 18n french strings for layout/application.html
> I18n support for layout/application.html view

- app/controllers/moderations_controller.rb
- app/models/moderation.rb
- app/views/moderations/index.html.erb
- config/locales/en.yml
- config/locales/fr.yml
- Support for i18n for the moderation view, the moderation controller and the moderation model
- Translations for new localized strings in both English and French
> I18n moderations

- db/migrate/20160704022756_change_story_columns.rb
- db/schema.rb
> Fix spec failure due to leaky ActiveRecord abstraction of booleans

- app/assets/javascripts/application.js.erb
- app/views/comments/_commentbox.html.erb
> Submit comment with ctrl+enter or cmd+enter [issue #273]

- db/schema.rb
Couldn't get a local copy to run until I did this.
> Change migration value in Schema

- app/controllers/comments_controller.rb
> comments: query where NOT EXISTS instead of NOT IN

- app/helpers/stories_helper.rb
> story: query moderation exists instead of count

- app/assets/stylesheets/application.css
Bug visible on desktop on https://lobste.rs/s/rjpb0o/node_js_is_windows_3_1_all_over_again
Sorry, I should have tested on more data before submitting the original PR.
> comments: fix alignment of deeply nested comments

- app/assets/stylesheets/application.css
- app/assets/stylesheets/mobile.css
- app/views/stories/show.html.erb
Tested:
* Top-level reply on desktop
* Top-level reply on mobile
* Nested reply on desktop
* Nested reply on mobile
> Comment reply alignment

- app/assets/stylesheets/application.css
- app/assets/stylesheets/mobile.css
- app/views/comments/_comment.html.erb
- app/views/comments/threads.html.erb
- app/views/stories/show.html.erb
> Tree lines on /threads, not /comments

- app/assets/javascripts/application.js.erb
**Before (list):**
**Before (comments section):**
**After (list):**
**After (comments section):**
> story: make flag popup opaque for negative score

- app/models/user.rb
- app/views/users/show.html.erb
- spec/models/user_spec.rb
Per discussion https://lobste.rs/s/2somjr/5_ways_developers_waste_more_than_20_their#c_odxdsb and on IRC.
Future work (future PRs) could include checking domain names.
> user: add method is_heavy_self_promoter?

- lib/tasks/fake_data.rake
This is for issue #414 (text only stories).
> Adding text only stories to fake_data task

- app/assets/javascripts/application.js.erb
- app/assets/stylesheets/application.css
- app/views/comments/_comment.html.erb
- app/views/comments/_postedreply.html.erb
> comments: update parent tree line on reply

- app/models/story.rb
How does this look?
closes #419
> Use parameterize in title_as_url

- app/assets/javascripts/application.js.erb
- app/controllers/comments_controller.rb
- app/views/comments/_commentbox.html.erb
> comments: fix tree lines on edit

- db/migrate/20180131203555_fix_doffed_at.rb
> fix migration datetime value

- app/controllers/settings_controller.rb
- app/views/settings/index.html.erb
Alternative to #476 not requiring JavaScript.
Meant to address issue #466.
> settings: "I am sure" checkbox to delete account

- .gitignore
- Gemfile
- Gemfile.lock
@jtopgi and I (and others I assume) use byebug for development / testing.
> add byebug to development

- config/initializers/new_framework_defaults_5_2.rb
Fixes 2 of the issues at: https://github.com/lobsters/lobsters/issues/509
I enabled the sqlite3 option as well since I think it doesn't affect lobsters.
> Active record cache versioning

- Gemfile
- Gemfile.lock
- config/boot.rb
https://github.com/lobsters/lobsters/issues/512
related to the rails 5.2 upgrade
> add bootsnap

- app/models/downvoted_commenters.rb
> remove unneeded column from query, fixes #529

- app/controllers/comments_controller.rb
these lines of codes appeared twice
> Remove duplicated before action

- app/models/invitation_request.rb
`InvitationRequest#email` is used by `InvitationRequestMailer`
> InvitationRequest: Validate presence of email

- app/models/hat.rb
- app/models/hat_request.rb
- app/models/hidden_story.rb
- app/models/invitation.rb
- app/models/message.rb
- app/models/mod_note.rb
- app/models/saved_story.rb
- app/models/story.rb
These are all covered by the `belongs_to` directive.
> Remove redundant validations

- script/send_new_webmentions
There is a RuboCop violation that is broken on [master](https://travis-ci.org/lobsters/lobsters/builds/436689242?utm_source=github_status&utm_medium=notification).
This fixes it 😄
> Fix Rubocop violation on master

- app/views/search/index.html.erb
This was bothering me so i fixed it real quick
> Use code tags instead of backticks

- app/assets/javascripts/application.js.erb
> prevent flag menu to inherit opacity

- app/models/story.rb
> return empty array when there's no similar stories

- extras/prohibit_safe_navigation.rb
> Fix #599, rubocop in production mode

- app/controllers/stories_controller.rb
- spec/features/comment_spec.rb
- spec/support/authentication_helper.rb
> Make merged votes voteable

- app/views/signup/invited.html.erb
> Fix #622 by renaming the invitation_code hidden field

- app/views/tags/_form.html.erb
Small PR to fix #633 
because "mode:" is an invalid function for method form_with
> Update _form.html.erb for tags_controller

- lib/tasks/fake_data.rake
Small PR to add some more fake data. I'm learning Rails and making progress on #414 at the same time!
(Also I reduced the number of stories, 1000 takes forever and doesn't make the site look any more realistic.)
> Fake Data: Hats, Comments

- db/seeds.rb
Automatically gives them enough karma to take all the mod actions + makes it old enough to take mod actions.
I found this was weird working on #630 trying to figure out what "downvoting" was.
> Make seed admin user "super"

- README.md
> Adds more macOS specific mysql2 instructions

- app/controllers/stories_controller.rb
- extras/markdowner.rb
- spec/features/submit_story_spec.rb
- spec/models/markdowner_spec.rb
> Replace images in story description with text links [#645]

- app/views/stories/_listdetail.html.erb
https://lobste.rs/s/bnze9m/suggestion_title_attributes_on
> Add a title attribute to the upvote button

- app/views/home/about.html.erb
I added a bit in the about page about needing 50 karma to downvote. 😊
> Add mention of the karma threshold for downvoting

- app/controllers/application_controller.rb
Add username to exception_notifications (fixes #676)
> Add username to exception notifications

- app/models/story.rb
- spec/models/story_spec.rb
This should fix the issue described in #683
> Bug fix: merged story can end up with an incorrect comments count

- app/assets/stylesheets/application.css
> Better readability for success flash messages

- README.md
> Typo: replaced a dot with a slash

- app/controllers/login_controller.rb
> Let's also ban their account.
> typo in login_controller.rb: s/acocunt/account/

- script/mail_new_activity.rb
> Make mail_new_activity no-op silently

- app/views/home/about.html.erb
> Fix broken anchor link in about page.

- app/controllers/stories_controller.rb
- spec/controllers/merge_stories_controller_spec.rb
> Fix bug allowing users to vote on, hide or save merged stories. (#739)

- app/models/story_repository.rb
- spec/models/story_repository_spec.rb
Also adds a simple spec for `.tagging`.
> Fixes #733 by refactoring the tagged query

- app/models/comment.rb
- app/models/hat.rb
- app/models/hat_request.rb
- spec/factories/hat_request.rb
- spec/models/comment_spec.rb
- spec/models/hat_request_spec.rb
- spec/models/hat_spec.rb
This adds validation and tests for the Comment, Hat, and HatRequests model to fix some parts of #745
> Add validation for comments, hats, hat requests

- .rubocop.yml
- Gemfile.lock
- app/controllers/keybase_proofs_controller.rb
- spec/models/search_spec.rb
> bump rubocop

- spec/requests/users_controller_spec.rb
I wanted to learn more about request specs (due to https://github.com/lobsters/lobsters/issues/704) and how they differ from controller specs.
> add initial requests spec for the users controller

- spec/factories/invitation.rb
- spec/factories/invitation_request.rb
- spec/models/invitation_request_spec.rb
- spec/models/invitation_spec.rb
Modified `Invitation` and `InvitationRequest` tests according to @pushcx comments on #754 
Also included tests to check if factory generates good models (fixed factory as well)
Should I add tests for all the validations on the models or is this enough?
> Improved Invitation and InvitationRequest tests

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
from the comment in https://github.com/lobsters/lobsters/pull/751#issuecomment-539983909
> handle request for unknown formats properly

- lib/tasks/fake_data.rake
This contributes to https://github.com/lobsters/lobsters/issues/414 by adding replies to comments and user-deleted stories
> add replying comments and deleted stories

- app/views/layouts/_footer.html.erb
Add button to reach the tags page at the footer adjacent to the Hats button.
> Create a tag button in footer

- lib/tasks/fake_data.rake
moderators as a mod of users, moderations section began below
> add moderators and moderations of comments

- spec/rails_helper.rb
- spec/requests/settings_spec.rb
- spec/requests/stories_spec.rb
- spec/requests/tags_spec.rb
- spec/support/authentication_helper.rb
I am not sure how to meaningfully reproduce the application controller spec however. See: https://github.com/rspec/rspec-rails/issues/2024
> Convert several controller specs to request specs

- app/controllers/home_controller.rb
- config/routes.rb
Adds a new route for returning the RSS feed for /top submissions
> Feat: add RSS feed for /top submissions

- app/controllers/home_controller.rb
- app/views/stories/_listdetail.html.erb
- config/routes.rb
- spec/controllers/home_controller_spec.rb
- spec/requests/home_spec.rb
Resolves the two issues noticed during the deploy this morning:
* Adds a second test which runs through Journey 
* Updates the constraint on the route to allow for `.`s in domains to propagate to the `domain` parameter.
> Change domain constraint to allow for dots

- app/models/story.rb
- app/models/user.rb
- app/models/vote.rb
- spec/models/story_spec.rb
- spec/models/user_spec.rb
- spec/models/vote_spec.rb
Validations to fix #745.
I wasn't sure whether to add one for password_digest as that's internally generated, but that can be done too.
> Add validations for vote, story, user

- app/models/moderation.rb
- spec/factories/domain.rb
- spec/models/moderation_spec.rb
> add one_foreign_key_present validator to moderation model

- spec/models/user_spec.rb
> Fix broken test

- app/controllers/invitations_controller.rb
> Log error when creating/sending an invitation fails

- Gemfile
- Gemfile.lock
- fixtures/vcr_cassettes/render_expected_kb_username.yml
- spec/requests/keybase_proofs_spec.rb
- spec/support/vcr.rb
Fix https://github.com/lobsters/lobsters/issues/863
> fix keybase spec

- lib/tasks/fake_data.rake
Just a small fix for error encountered when setting up this project.
Faker reference: https://github.com/faker-ruby/faker/blob/3f72057a7522849243c4c7fa8d0527580588cbcf/lib/faker/default/internet.rb#L44-L47
> Update deprecrated Faker params

- README.md
87f2404c08b49bd3746c7cf1c96ccdce5d5c8436 bumped the Ruby version from 2.3.3 to 2.7.0, but it looks like the Readme was never updated.
> Update the version of Ruby in the Readme

- app/assets/stylesheets/application.css
- app/assets/stylesheets/local/lobsters.css
> Add Lobsters dark mode

- config/sitemap.rb
I'm completely unclear whether this is sufficient to fix sitemap.rb, and idly wonder if there is any testing that could be done that would have caught this mistake.
Please provide feedback on how this fix can be improved.
> sitemap.rb: the upvotes column in the stories model is now score.

- app/views/home/about.html.erb
Just a small typo fix I noticed when reading the About page this morning.
> Fix typo on about page

- app/models/category.rb
Removes the noise from the tests.
> Cleanup deprecation notices when running tests.

- app/views/home/about.html.erb
The other use on this page uses vs. h/t geoffwozniak.
> about.html: use vs. not vs for versus

- app/models/story.rb
The new method definition should return the same value while being simple, readable, and intuitive w.r.t. the name of the function.
> Rewrite small method `Story#can_be_seen_by_user?`

- app/models/search.rb
> search.rb: association is :story_text, not :story_texts.

- lib/tasks/daily_maintenance.rake
> s/dail/daily/ for daily_maintenance task.

- app/assets/stylesheets/application.css
- app/helpers/application_helper.rb
- app/views/stories/_listdetail.html.erb
Fixes #849. [More information is in my comment on the relevant issue](https://github.com/lobsters/lobsters/issues/849#issuecomment-725578055)
- Passes rubocop/ruumba
- Passes tests `272 examples, 0 failures, 3 pending`
> Switch to breaking long words in browsers

- README.md
> Update Rails version description

- app/models/user.rb
- lib/tasks/fake_data.rake
- spec/models/user_spec.rb
was broken because user accounts were not old enough to post new urls
also simplify code a bit
👋
> fix rake fake_data

- app/views/home/chat.html.erb
- public/500.html
> Add Libera Chat info to /chat and the 500 page

- app/controllers/settings_controller.rb
- spec/features/settings_spec.rb
> Fixes involuntary user deletion and comment disown. Closes #1004

- app/controllers/users_controller.rb
Fixes #1005 
Hi @pushcx, does this fix work?
Thanks!
> Fix: Case bug viewing profile/standing page 

- app/views/home/about.html.erb
- app/views/home/chat.html.erb
Fixed a couple of small typos that were bothering me. 
I'd appreciate it if you send an invite to contact[at]linuxstans.com :) thanks
> Fixed small typos

- app/assets/stylesheets/application.css.erb
> fix horizontal alignment of upvote buttons

- app/controllers/hats_controller.rb
- app/models/hat_request.rb
- app/views/hats/requests_index.html.erb
- Common reason box for hat approval and rejection.
- Change the reason box param name from rejection_comment to reason.
- Change approve_by_user! to approve_by_user_for_reason! with reason param.
> Message for hat approvals

- app/views/tags/index.html.erb
This PR fixes wrong category edit link paths for the tag list page.
> Fix wrong category edit paths for the tag list page

- spec/features/filter_spec.rb
Closes https://github.com/lobsters/lobsters/issues/1055
> Add tests for /filters page

- app/assets/stylesheets/application.css.erb
- app/views/stories/_listdetail.html.erb
Hotfix Z index problems with the Archive Dropdown on stories with a negative rating
> Fix Archive Dropdown Z-index

- app/views/stories/suggest.html.erb
> fix tags selection dropdown on suggest page

- app/controllers/comments_controller.rb
- app/views/comments/index.html.erb
The subnav is not showing on the Upvoted Comments page. (Not showing up since https://github.com/lobsters/lobsters/commit/91891dc214b39ad1a673b6fea0a68c6e0f13c221)
refer to https://github.com/lobsters/lobsters/blob/b731305b941e65e7e76185cea3329f7e3fefd2ad/app/controllers/home_controller.rb#L285-L291
> Fix subnav of Upvoted Comments

- app/views/stories/_form.html.erb
> Correct html escape on fetch title

- app/helpers/interval_helper.rb
Very small update, completely understand if it seems not worth merging. This just updates `app/helpers/interval_helper.rb` to accept the formatting given in examples from [this comment](https://lobste.rs/s/bb80bu/quick_scan_through_lobsters_s_source_code#c_162azj). I only submit this as I was confused when trying to click through that comment why hours wasn't actually working. 
Fixes #958
> Update interval_helper to accept hours.

- app/views/search/index.html.erb
- Fix current page pagination
Fixes #1208
JFI: It'd be nice if you added the Hacktoberfest label to your repository to have more people contributing to it.
> fix current page pagination

- app/views/stories/_listdetail.html.erb
- spec/features/read_story_spec.rb
Closes https://github.com/lobsters/lobsters/issues/1202
Screenshots:
Removed story previously saved; `unsave` link available.
Removed story; `save` link still unavailable.
> Display unsave link for previously saved stories

- app/assets/javascripts/application.js.erb
- app/assets/stylesheets/application.css.erb
- app/views/stories/_form.html.erb
- Bring tag colors to edit form https://github.com/lobsters/lobsters/issues/1222
> Feature - Bring tag colors to edit form

- extras/utils.rb
- spec/extras/normalize_url_spec.rb
Related to #1223.
Will normalize rfc-editor.org links to reduce duplicate entries being posted.
> Normalize rfc-editor.org links

- app/helpers/users_helper.rb
Added "(" for the moderator line.
After seeing a quick PR to fix it. https://lobste.rs/moderators
> Forgot a "("

- public/504.html
Howdy, I removed an old error/info message as seen on the 504.html page
> Removed old error status message

- app/controllers/stories_controller.rb
- app/controllers/story_urls_controller.rb
- config/routes.rb
This needs tests, but is a start.
You can test the new endpoint locally with `curl`:
curl -isSL "http://localhost:3000/stories/all?url=https://example.com"
> Support looking up all stories by their URL.

- app/controllers/hats_controller.rb
- app/views/hats/edit.html.erb
- app/views/hats/index.html.erb
- config/routes.rb
- spec/features/edit_hat_spec.rb
> Web UI hat editing

- extras/prohibit_form_for_and_form_tag.rb
> Stop loading rubocop in production workers

- app/views/stories/_form.html.erb
Suggest that submitters make baity titles, especially negative baity titles, less baity.
I'm not really sure about the wording/order of things here--it feels weird to put it at the beginning--but I've procrastinated for like two weeks without thinking of a better version.
> Add story guideline about clickbait titles

- extras/sponge.rb
> Sponge: properly encode POST data

- app/models/user.rb
- spec/models/user_spec.rb
Fix #1344 
Added underscore and dash collide validation in `User` model.
> Issue #1344 Consider - and _ a collision in usernames

- .active_record_doctor.rb
- app/models/domain.rb
- app/models/link.rb
- app/models/message.rb
- app/models/origin.rb
- app/models/story.rb
- app/models/user.rb
- db/migrate/20241016194903_add_index_banned_by_user_id_foreign_key_in_origins.rb
- db/migrate/20241016200032_active_record_doctor_missing_foreign_keys.rb
- db/migrate/20241017011246_active_record_doctor_incorrect_length_validation.rb
- db/schema.rb
From issue #1281 , this is a small contribution to fix database issues as flagged by `active_record_doctor`
Note:
There are still some warnings to tackle for the remaining detectors, i want to tackle that next week.
> Database consistency fixes

- config/application.rb
- lib/tasks/update_banned_url_shorteners.rake
> Update list of banned url shorteners in rake task

- app/assets/javascripts/application.js.erb
- app/assets/stylesheets/application.css.erb
- app/controllers/stories_controller.rb
- app/views/home/index.html.erb
- app/views/search/index.html.erb
- app/views/stories/_listdetail.html.erb
- spec/features/story_spec.rb
- spec/requests/stories_spec.rb
issue #1355 
- remove previous `story disowner` js
- style `disown` button
- update specs
> Remove blank href from story disown flow

- app/controllers/hat_requests_controller.rb
- app/views/hat_requests/index.html.erb
- config/routes.rb
- spec/features/hat_request_spec.rb
> Fix: Hat request approval & rejection

- app/controllers/application_controller.rb
- app/controllers/story_urls_controller.rb
- spec/requests/stories_spec.rb
- spec/requests/story_urls_spec.rb
> Fix exception raised in StoryUrlsController#all

- app/controllers/mod/stories_controller.rb
- app/controllers/stories_controller.rb
- app/views/mod/stories/edit.html.erb
- app/views/stories/edit.html.erb
- config/routes.rb
- spec/requests/mod/stories_spec.rb
> Split undelete story controller

- app/javascript/application.js
Values are being passed as JSON string, so parse the string to JSON
> Fix #1446 (broken flag reasons)

- app/assets/stylesheets/application.css
I replaced the wrong comma in two lines in #1448.
> fix typo in #1448

- app/assets/stylesheets/application.css
But don't make it both dotted and light.
Related to
- commit 96cf0b3
- issue #1404
I remembered this due to recent CSS changes :-)
> CSS: Make <hr> lighter than the default.

- app/controllers/comments_controller.rb
- app/controllers/filters_controller.rb
- app/controllers/home_controller.rb
- app/controllers/mod_controller.rb
- app/controllers/mod_notes_controller.rb
- app/controllers/moderations_controller.rb
- app/controllers/stories_controller.rb
- app/controllers/tags_controller.rb
- app/controllers/users_controller.rb
- app/models/comment.rb
- app/models/flagged_commenters.rb
- app/models/message.rb
- app/models/mod_note.rb
- app/models/story.rb
- app/models/story_repository.rb
- app/models/user.rb
- db/migrate/20250124063340_add_last_comment_at_to_stories.rb
- db/schema.rb
Replaces SQL string with activerecord friendly query 
Reference 
https://github.com/lobsters/lobsters/issues/539
> Replaces SQL string with activerecord friendly query

- app/controllers/stats_controller.rb
#539 Replace raw SQL in StatsController with ActiveRecord
> remove raw_sql used to generate graph data in stats page

- README.md
To avoid confusion, I make this PR to add Zulip site link in the Readme.
> Add missing link to Zulip site in Readme

- Dockerfile.dev
- Makefile
- README.md
- docker-compose.yaml
- docs/setup_with_docker.md
This PR 
- adds development dockerfile for local environment.
> Create docker workflow for local development

- CONTRIBUTING.md
CONTRIBUTING.md had a broken markdown and a bare html link. I made them both markdown. I also tidied up a couple of lints.
> Fix a couple of links the CONTRIBUTING.md and clean up the file

- app/controllers/comments_controller.rb
- app/controllers/home_controller.rb
- app/views/comments/index.html.erb
- db/migrate/20250302102016_add_edit_last_read_newest.rb
- db/schema.rb
- spec/factories/user.rb
- spec/features/newest_spec.rb
> Add 'Last Read' marker to /comments 

- app/views/comments/_commentbox.html.erb
> fix indentation in _commentbox.html.erb

- app/controllers/users_controller.rb
These classes don't impact the styling, so are possibly candidates for removal altogether.
> Use the correct classes on the title of user profiles

- app/views/stories/_form.html.erb
[AwesomeScreenshot-3_4_2025,11_19_22pm.webm](https://github.com/user-attachments/assets/87c31f11-e77b-4b6a-9216-64c85fc61bf1)
> fix(issue-1505): story form url field retention

- app/views/stories/_singledetail.html.erb
This PR is to fix the issue reported here: https://github.com/lobsters/lobsters/issues/1513#issuecomment-2788274255
> fix: add missing a tag in story comments page

- Gemfile
- Gemfile.lock
This fixes errors from Brakeman, following [this suggestion](https://github.com/presidentbeef/brakeman/issues/1927#issuecomment-2794239272) from @presidentbeef.
> Install Prism 1.4.0 ourselves

- app/assets/stylesheets/application.css
- app/models/comment.rb
- app/views/comments/_comment.html.erb
- app/views/comments/_postedreply.html.erb
- app/views/comments/_threads.html.erb
- app/views/settings/index.html.erb
- app/views/signup/invite.html.erb
- app/views/stories/show.html.erb
- app/views/users/_invitationform.html.erb
- app/views/users/show.html.erb
I've started with the user profile page, but I plan to gradually cover all of the pages in this branch. Alongside using CSS grid, I've aimed to stop depending on `line-height` and `<br>` for page layout. The avatar is still floated at the moment, though given the grid cannot wrap around it with the current setup, that could be changed without affecting the (new) design.
I'm no designer, but I tried to make things space out more logically. For instance, in the mobile single-column view, there is more space between a heading and the previous item than between a heading and its item. I'm very much open to feedback both on the visual design, and the CSS implementation.
As well as this not covering every page yet, I'm still not 100% happy with the new profile page (hence the draft PR, and CSS …
> Begin porting pages to CSS Grid

- app/controllers/comments_controller.rb
- app/controllers/home_controller.rb
- app/views/comments/index.html.erb
- app/views/home/index.html.erb
- spec/features/newest_spec.rb
> Last read line fix by maintaining pagination

- app/assets/stylesheets/application.css
Sorry about that! Thanks @JulianWgs for spotting this during office hours.
> Fix tree lines with added <div>

- app/assets/stylesheets/application.css
I'd need to dig more into it, but I'm not sure what the differences between `link_post` and `button_to` are, and whether we can switch to only using one of them.
> Fix styling of disown button

- app/assets/stylesheets/application.css
- app/views/settings/index.html.erb
- app/views/signup/invite.html.erb
- app/views/users/_invitationform.html.erb
- app/views/users/show.html.erb
Bringing back some of the changes from #1508 that didn't involve subgrid.
This PR includes the bug fix from a54b145c18735872528e09df24247da6d7bc63fa.
> Use CSS Grid for user profiles and settings

- spec/models/user_spec.rb
Fixup for f174623be9d627509d79ed18d80e2ec5cfaa7e39
> Fix user test to reflect increased banned_reason max size

- app/assets/stylesheets/application.css
- app/views/hat_requests/index.html.erb
- app/views/hat_requests/new.html.erb
- app/views/hats/doff.html.erb
- app/views/hats/edit.html.erb
- app/views/hats/index.html.erb
This is work towards #1279.
<details>
<summary>Uninteresting screenshots</summary>
</details>
> Lay out the pages for hats and hat requests using CSS Grid

- app/views/stories/show.html.erb
The note shown on hidden stories explaining that it is hidden and what that means had broken grammar, I reworded it slightly to fix that.
> Fix note on hidden stories

- app/controllers/home_controller.rb
- app/models/story.rb
- app/models/story_repository.rb
- spec/controllers/home_controller_spec.rb
- spec/models/story_repository_spec.rb
- spec/models/story_spec.rb
https://github.com/lobsters/lobsters/issues/1523
Move `active` method from the repository to Story model as a scope.
> Refactory Story Repository: active method

- app/controllers/home_controller.rb
- app/models/story.rb
- app/models/story_repository.rb
- spec/controllers/home_controller_spec.rb
- spec/models/story_spec.rb
https://github.com/lobsters/lobsters/issues/1523
Move `saved` method from the repository to Story model as a scope.
> Refactory story repository saved method

- lib/tasks/data_stats.rake
Performance has come up a couple of times as a topic of interest in the #539 and now as part of #1076 . I realized I don't really have a good way to test and see performance issues locally. The fake_data task isn't enough since it produces 0 rows in the mentioned view.
I wrote up a script that I hope you could review/run on lobsters and paste the stats output somewhere so that I could come up with a more realistic data set for my testing.
run with `rails data_stats` and the output file will be under /tmp/stats.json
This would allow me to work on a script that would generate more realistic data so that I can see the performance problems locally for debugging and testing.
> Statistics collection script

- CONTRIBUTING.md
As discussed on IRC the other day.
I opted to just copy the same wording from the pull request template, but if desired I can expand it.
> Mention that LLM-based changes are not welcome.

- app/models/user.rb
Closes #933
This is a duplicate of #1177 by @msfjarvis
Before:
```
{"username":"test","created_at":"2025-05-03T19:13:57.000-05:00","is_admin":true,"is_moderator":true,"about":"**testing**! [my website](https://zac.gorak.us)","avatar_url":"/avatars/test-100.png","invited_by_user":null}
```
After:
```
{"username":"test","created_at":"2025-05-03T19:13:57.000-05:00","is_admin":true,"is_moderator":true,"about":"\u003cp\u003e\u003cstrong\u003etesting\u003c/strong\u003e! \u003ca href=\"https://zac.gorak.us\" rel=\"ugc\"\u003emy website\u003c/a\u003e\u003c/p\u003e\n","avatar_url":"/avatars/test-100.png","invited_by_user":null}
```
This creates more consistent output for json files.
> Use linkified_about for user json

- config/initializers/00_zeitwerk.rb
- config/puma.rb
- spec/models/markdowner_spec.rb
Some minor but common stuffs may help people deploy the codebase in production.
background: https://github.com/lobsters/lobsters/pull/1667#issuecomment-3077897938
> fix: make it eaiser to deploy in container

- app/controllers/home_controller.rb
- app/models/story.rb
- app/models/story_repository.rb
- config/brakeman.ignore
- spec/models/story_spec.rb
https://github.com/lobsters/lobsters/issues/1523
Move `top` method from the repository to Story model as a scope.
> Refactor story repository: top

- app/controllers/messages_controller.rb
- app/controllers/notifications_controller.rb
- app/jobs/notify_message_job.rb
- app/models/comment.rb
- app/models/message.rb
- db/migrate/20250728030009_mark_read_notifications.rb
- db/schema.rb
- spec/controllers/messages_controller_spec.rb
- spec/controllers/notifications_controller_spec.rb
- spec/jobs/notify_message_job_spec.rb
related to https://github.com/lobsters/lobsters/issues/1076#issuecomment-3114031461
I think this is still a work in progress, but wanted to get feedback for it.
> Link message read status with notifications.

- .github/workflows/check.yml
- README.md
- app/controllers/notifications_controller.rb
- app/views/about/about.html.erb
Set the comment.current_vote and comment.vote_summary that the comment partial depends on to work properly
Should fix https://github.com/lobsters/lobsters/issues/1076#issuecomment-3143820327
> highlight user upvoted comments in the notifications page

- app/helpers/hats_helper.rb
- app/models/hat.rb
- app/views/comments/_comment.html.erb
- app/views/comments/_threads.html.erb
- app/views/hats/doff.html.erb
- app/views/hats/index.html.erb
- app/views/messages/index.html.erb
- app/views/messages/show.html.erb
- app/views/users/show.html.erb
> [1581] Extract to_html_label from hat model to hats helper

- CONTRIBUTING.md
- README.md
- config/database.yml.sample
- docs/setup_with_docker.md
I'm getting ready to pick up an issue, but first here are improvements around friction that I ran into during setup.
This PR improves the setup experience:
- Avoids a database setup error from `bin/setup` by including the default database username and password in the sample `database.yml`.
- If the sample `database.yml` should not be changed, I made [a separate prior commit](https://github.com/lobsters/lobsters/pull/1722/commits/d6038eda164f184d9661f23bdb53baee0d487ebc) where a point is simply added to the README about manually editing `database.yml` to add a username and password, after the setup error occurs. (This step [is already in the Docker setup instructions](https://github.com/fpsvogel/lobsters/blob/main/docs/setup_with_docker.md#:~:text=Add%20the%20below%20code%20to%20yoru%20deve …
> Improve setup, instructions

- CLAUDE.md
Forgot to commit this bit of #1733.
> Symlink CLAUDE.md
